### ISSUE TITLE
`e build` fails when Goma isn't running

### ISSUE THREAD

**Issue by samuelmaddock** [electron/build-tools#113]
OS: Windows 10 64-bit (Build 18362)

After restarting my machine, Goma will no longer be running. If I attempt to run `e build`, it will fail when compiling the first module.
```
gomacc_common.cc:166] failed to connect to: C:\Users\Sam\AppData\Local\Temp\goma\goma.ipc: 10061
compiler_proxy isn't running. Run 'goma_ctl.bat ensure_start'.
ninja: build stopped: subcommand failed.
ERROR Error: Command failed: ninja electron
    at checkExecSyncError (child_process.js:630:11)
    at Object.execFileSync (child_process.js:648:15)
    at Object.depotExecFileSync [as execFileSync] (D:\work\build-tools\src\utils\depot-tools.js:91:16)
    at runNinja (D:\work\build-tools\src\e-build.js:61:9)
    at Object.<anonymous> (D:\work\build-tools\src\e-build.js:105:3)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
```

To fix this, I need to run the following
```
build-tools/third_party/goma/goma_ctl.py ensure_start
```

Starting a build should check whether Goma is running, if not disabled, before continuing.

**Comment by codebytere** [comment]
@samuelmaddock does this happen on latest versions? That logic was added a while ago: https://github.com/electron/build-tools/commit/635d114e4e1573aed2052141489bdac15bdd26ab

**Comment by samuelmaddock** [comment]
The check to start Goma does run now, but never seems to complete on the first run.
```
D:\electron>e build
Running "goma_ctl.py ensure_start" in C:\Users\Sam\.electron_build_tools\third_party\goma
Terminate batch job (Y/N)? y

D:\electron>e build
Running "goma_ctl.py ensure_start" in C:\Users\Sam\.electron_build_tools\third_party\goma
Not logged in
Running "ninja -j 200 electron" in D:\electron\src\out\Testing
```

I can reproduce the first run issue by either restarting my machine or killing `compiler_proxy.exe` in task manager.

**Comment by samuelmaddock** [comment]
The last issue I mentioned is already covered by #91. Going to close this issue since `e build` works without failing.
