### ISSUE TITLE
`e init` fails on Windows 1903

### ISSUE THREAD

**Issue by strega-nil** [electron/build-tools#131]
In cmd:

```
> set PATH=C:\Users\Nicole Mazzuca\src\langs\electron-build-tools\src;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\LLVM\bin;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Users\Nicole Mazzuca\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\Nicole Mazzuca\AppData\Local\Programs\Python\Python38\;C:\Users\Nicole Mazzuca\AppData\Roaming\local\bin;C:\Users\Nicole Mazzuca\.cargo\bin;C:\Users\Nicole Mazzuca\AppData\Local\Microsoft\WindowsApps;C:\Users\Nicole Mazzuca\AppData\Roaming\npm;C:\Users\Nicole Mazzuca\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Nicole Mazzuca\AppData\Local\Microsoft\WindowsApps;C:\Users\Nicole Mazzuca\.dotnet\tools;C:\Program Files (x86)\Vim\vim80

> del /S /Q ..\electron
Deleted file - C:\Users\Nicole Mazzuca\src\langs\electron\.gclient

> del /S /Q configs\*
Deleted file - C:\Users\Nicole Mazzuca\src\langs\electron-build-tools\configs\evm.testing.json

> e init --root=..\electron --bootstrap testing
New build config testing created in C:\Users\Nicole Mazzuca\src\langs\electron-build-tools\configs\evm.testing.json
ERROR Error: spawnSync node ENOENT
    at Object.spawnSync (internal/child_process.js:1045:20)
    at spawnSync (child_process.js:597:24)
    at Object.execFileSync (child_process.js:624:15)
    at Object.<anonymous> (C:\Users\Nicole Mazzuca\src\langs\electron-build-tools\src\e-init.js:184:16)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by MarshallOfSound** [comment]
@strega-nil Your `PATH` doesn't appear to have `node` on it.  Adding that to your path should fix this.
