### ISSUE TITLE
switch branch or tags fail

### ISSUE THREAD

**Issue by bigben0123** [electron/build-tools#145]
On windows, when I use
e init master-testing --root=~/src/electron
e sync
It's ok.

Now I want to swith to branch 7-3-x. I can't figure out where to go.

I use " e sync --revision 7-3-x", it shows checkout 7-3-x success. But source code is not update. When I force sync, it error.
or should I modify .gclient to http://github.com/electron/electron@7-3-x on unmanaged url?
Does unmanaged affect switch branch?

I don't find any tip on internet.

**Comment by bigben0123** [comment]
I tried this:
modify .gclient  url=https://github.com/electron/electron/tree/7-3-x
then:
  e sync -f -vvvv

`
Hook 'vpython.bat src/tools/remove_stale_pyc_files.py src/android_webview/tools src/build/android src/gpu/gles2_conform_support src/infra src/ppapi src/printing src/third_party/blink/renderer/build/scripts src/third_party/blink/tools src/third_party/catapult src/third_party/closure_compiler/build src/tools' took 10.01 secs
subprocess2(154) __init__:vpython.bat src/buildtools/ensure_gn_version.py git_revision:152c5144ceed9592c20f0c8fd55769646077569b;  cwd=C:\dev\electron7
________ running 'vpython.bat src/buildtools/ensure_gn_version.py git_revision:152c5144ceed9592c20f0c8fd55769646077569b' in 'C:\dev\electron7'
subprocess2(154) __init__:vpython.bat src/build/vs_toolchain.py update --force;  cwd=C:\dev\electron7
________ running 'vpython.bat src/build/vs_toolchain.py update --force' in 'C:\dev\electron7'
Windows toolchain out of date or doesn't exist, updating (Pro)...
  current_hashes:
  desired_hash: 418b3076791776573a815eb298c8aa590307af63
Failed to retrieve file: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "src/build/vs_toolchain.py", line 560, in <module>
    sys.exit(main())
  File "src/build/vs_toolchain.py", line 556, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "src/build/vs_toolchain.py", line 504, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Users\Administrator\.electron_build_tools\third_party\depot_tools\bootstrap-3_8_0_chromium_8_bin\python\bin\Lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Administrator\\.vpython-root\\5550ac\\Scripts\\python.exe', 'C:\\dev\\electron7\\src\\third_party\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'C:\\dev\\electron7\\src\\build\\win_toolchain.json', '418b3076791776573a815eb298c8aa590307af63', '--force']' returned non-zero exit status 1
Error: Command 'vpython.bat src/build/vs_toolchain.py update --force' returned non-zero exit status 1 in C:\dev\electron7
ERROR Error: Command failed: python C:\Users\Administrator\.electron_build_tools\third_party\depot_tools\gclient.py sync --with_branch_heads --with_tags -vv -f -v -v -v -v
    at checkExecSyncError (child_process.js:630:11)
    at Object.execFileSync (child_process.js:648:15)
    at Object.depotExecFileSync [as execFileSync] (C:\Users\Administrator\.electron_build_tools\src\utils\depot-tools.js:95:16)
    at runGClientSync (C:\Users\Administrator\.electron_build_tools\src\e-sync.js:37:9)
    at Object.<anonymous> (C:\Users\Administrator\.electron_build_tools\src\e-sync.js:50:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
`

The error is:
Windows toolchain out of date or doesn't exist, updating (Pro)...
  current_hashes:
  desired_hash: 418b3076791776573a815eb298c8aa590307af63
Failed to retrieve file: HTTP Error 403: Forbidden

**Comment by bigben0123** [comment]
I just use this windows 10 to download source and don't need to build so I don't install any windows sdk or vs2017. I think gclient sync runhooks don't require winsdk. 
I read vs_toolchain.py and there are so many sdk enviroment in it.

I download source succeed with master nightly update.

**Comment by bigben0123** [comment]
I set env in config file: .electron_build_tools\configs\evm.electron7.json
{
  "goma": "none",
  "root": "D:\\dev\\electron-master\\electron",
  "origin": {
    "electron": "git@github.com:electron/electron.git",
    "node": "git@github.com:electron/node.git"
  },
  "gen": {
    "args": [
      "import(\"//electron/build/args/testing.gn\")"
    ],
    "out": "Testing"
  },
  "env": {
    "CHROMIUM_BUILDTOOLS_PATH": "D:\\dev\\electron-master\\electron\\src\\buildtools",
    "DEPOT_TOOLS_WIN_TOOLCHAIN": 0,
    "GIT_CACHE_PATH": "C:\\Users\\zhibin\\.git_cache"
  }
}


Now the error is:
________ running 'vpython.bat src/tools/clang/scripts/update.py' in 'C:\dev\electron7'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Win/clang-371202-8455294f-1.tgz .......... Done.
Traceback (most recent call last):
  File "src/tools/clang/scripts/update.py", line 336, in <module>
    sys.exit(main())
  File "src/tools/clang/scripts/update.py", line 332, in main
    return UpdateClang()
  File "src/tools/clang/scripts/update.py", line 270, in UpdateClang
    CopyDiaDllTo(os.path.join(LLVM_BUILD_DIR, 'bin'))
  File "src/tools/clang/scripts/update.py", line 230, in CopyDiaDllTo
    GetWinSDKDir()
  File "src/tools/clang/scripts/update.py", line 204, in GetWinSDKDir
    win_sdk_dir = vs_toolchain.SetEnvironmentAndGetSDKDir()
  File "C:\dev\electron7\src\build\vs_toolchain.py", line 518, in SetEnvironmentAndGetSDKDir
    SetEnvironmentAndGetRuntimeDllDirs()
  File "C:\dev\electron7\src\build\vs_toolchain.py", line 85, in SetEnvironmentAndGetRuntimeDllDirs
    os.environ['GYP_MSVS_OVERRIDE_PATH'] = DetectVisualStudioPath()
  File "C:\dev\electron7\src\build\vs_toolchain.py", line 173, in DetectVisualStudioPath
    version_as_year = GetVisualStudioVersion()
  File "C:\dev\electron7\src\build\vs_toolchain.py", line 163, in GetVisualStudioVersion
    ' Supported versions are: %s.' % supported_versions_str)
Exception: No supported Visual Studio can be found. Supported versions are: 15.0 (2017), 16.0 (2019).
Error: Command 'vpython.bat src/tools/clang/scripts/update.py' returned non-zero exit status 1 in C:\dev\electron7
ERROR Error: Command failed: python C:\Users\Administrator\.electron_build_tools\third_party\depot_tools\gclient.py sync --with_branch_heads --with_tags -vv -f
    at checkExecSyncError (child_process.js:630:11)
    at Object.execFileSync (child_process.js:648:15)
    at Object.depotExecFileSync [as execFileSync] (C:\Users\Administrator\.electron_build_tools\src\utils\depot-tools.js:95:16)
    at runGClientSync (C:\Users\Administrator\.electron_build_tools\src\e-sync.js:37:9)
    at Object.<anonymous> (C:\Users\Administrator\.electron_build_tools\src\e-sync.js:50:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)

my server just download source, not to build. Why it need install win sdk?

**Comment by bigben0123** [comment]
or how to set reversion in config file:

 "origin": {
    "electron": "git@github.com:electron/electron.git",
    "node": "git@github.com:electron/node.git"
  },


like :git@github.com:electron/electron.git@7-3-x

**Comment by guomh** [comment]
I have the same problem with you. When I was built Electron,I don't know how to change Electron 's version to build.
Do you know how?

**Comment by codebytere** [comment]
Unfortunately, at this point, Electron with build-tools can't be switched over to `7-3-x` owing to differences in dependencies (win toolchain, xcode etc) at the Chromium level. The normal flow:

```sh
$ git checkout 8-x-y
$ e sync -vvvv
$ e build
```

Should work as expected for all newer branches.
