### ISSUE TITLE
when running `e init` on a bootstrap that already exists, the path of how to progress is unclear

### ISSUE THREAD

**Issue by bnb** [electron/build-tools#150]
I've picked up build_tools a few times, either from fresh or after a few months. Each time, my brain goes to the same bootstrap name which ends up failing since it already exists. I can't tell if it being in some destroyed/incomplete state matters here, but that is usually the state of things when I'm trying to re-run it.

An example of the command I run once:
```
$ e init --root=~/electron --bootstrap local     
```

Then I get this: 
```
ERROR Error: Build config local already exists! (/Users/cyren/GitHub/electron/build-tools/configs/evm.local.json)
    at Object.<anonymous> (/Users/cyren/GitHub/electron/build-tools/src/e-init.js:152:11)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

It would be nice if there was:
- a way to either pick up where I left off with that `e init`, or
- a way to wipe that config

**Comment by MarshallOfSound** [comment]
I think if `root` doesn't exist but the `{bootstrap}` config does and already points at that `root` we should delete that config and recreate it automatically.

If it's pointing at a different root we can prompt them to choose a different name / overwrite the config.

**Comment by bnb** [comment]
@MarshallOfSound that sounds like a reasonable solution to me.
