### ISSUE TITLE
Goma fails to update on Windows when already running

### ISSUE THREAD

**Issue by samuelmaddock** [electron/build-tools#157]
When running build tools, it fails with the following error:
```
D:\electron\src>e build
ERROR Error: EPERM: operation not permitted, unlink 'C:\Users\Sam\.electron_build_tools\third_party\goma\compiler_proxy.exe'
    at Object.unlinkSync (fs.js:1052:3)
    at fixWinEPERMSync (C:\Users\Sam\.electron_build_tools\node_modules\rimraf\rimraf.js:213:13)
    at rimrafSync (C:\Users\Sam\.electron_build_tools\node_modules\rimraf\rimraf.js:314:28)
    at C:\Users\Sam\.electron_build_tools\node_modules\rimraf\rimraf.js:344:39
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\Sam\.electron_build_tools\node_modules\rimraf\rimraf.js:344:26)
    at rmdirSync (C:\Users\Sam\.electron_build_tools\node_modules\rimraf\rimraf.js:337:7)
    at fixWinEPERMSync (C:\Users\Sam\.electron_build_tools\node_modules\rimraf\rimraf.js:211:5)
    at Function.rimrafSync [as sync] (C:\Users\Sam\.electron_build_tools\node_modules\rimraf\rimraf.js:314:28)
    at Object.downloadAndPrepareGoma [as downloadAndPrepare] (C:\Users\Sam\.electron_build_tools\src\utils\goma.js:46:10)
```

I believe the Goma hash update likely caused this in 524810fa23ad2569b41bc1021a75ef5386dd029e

To fix it, I had to kill compiler_proxy.exe in task manager prior to running again.

**Comment by MarshallOfSound** [comment]
Hm yeah, if the goma hash does not match we should probably run `goma_ctl stop` 🤔
