### ISSUE TITLE
e build failed

### ISSUE THREAD

**Issue by AlvinZhangH** [electron/build-tools#163]
D:\electron\0827\000\build-tools-master>e build
Running "goma_ctl.py ensure_start" in D:\electron\0827\000\build-tools-master\third_party\goma
Not logged in
E0831 14:44:30.165356 11780 gomacc_common.cc:166] failed to connect to: C:\Users\ZWX953~1\AppData\Local\Temp\goma\goma.ipc: 10061
E0831 14:44:30.166384 11780 goma_ipc.cc:71] call failed: Failed to connect to C:\Users\ZWX953~1\AppData\Local\Temp\goma\goma.ipc
GOMA: port request failed. connect_success: 0, err: -1 Failed to connect to C:\Users\ZWX953~1\AppData\Local\Temp\goma\goma.ipc, http_return_code: 0
E0831 14:45:50.312211 12256 gomacc_common.cc:166] failed to connect to: C:\Users\ZWX953~1\AppData\Local\Temp\goma\goma.ipc: 10061
E0831 14:45:50.313288 12256 goma_ipc.cc:71] call failed: Failed to connect to C:\Users\ZWX953~1\AppData\Local\Temp\goma\goma.ipc
GOMA: port request failed. connect_success: 0, err: -1 Failed to connect to C:\Users\ZWX953~1\AppData\Local\Temp\goma\goma.ipc, http_return_code: 0
E0831 14:47:10.508966 14292 gomacc_common.cc:166] failed to connect to: C:\Users\ZWX953~1\AppData\Local\Temp\goma\goma.ipc: 10061
E0831 14:47:10.508966 14292 goma_ipc.cc:71] call failed: Failed to connect to C:\Users\ZWX953~1\AppData\Local\Temp\goma\goma.ipc
GOMA: port request failed. connect_success: 0, err: -1 Failed to connect to C:\Users\ZWX953~1\AppData\Local\Temp\goma\goma.ipc, http_return_code: 0
Traceback (most recent call last):
  File "goma_ctl.py", line 3194, in <module>
    sys.exit(main())
  File "goma_ctl.py", line 3189, in main
    goma.Dispatch(sys.argv[1:])
  File "goma_ctl.py", line 1434, in Dispatch
    self._action_mappings.get(args[0], self._DefaultAction)()
  File "goma_ctl.py", line 808, in _EnsureStartCompilerProxy
    self._GenericStartCompilerProxy(ensure=True, force_update=False)
  File "goma_ctl.py", line 767, in _GenericStartCompilerProxy
    self._env.ExecCompilerProxy()
  File "goma_ctl.py", line 2117, in ExecCompilerProxy
    return self._GetCompilerProxyPort(proc=proc)  # set the new gomacc_port.
  File "goma_ctl.py", line 1677, in _GetCompilerProxyPort
    raise e
__main__.Error: compiler_proxy is not ready? pid=12416
ERROR Error: Command failed: python goma_ctl.py ensure_start
Not logged in
E0831 14:44:30.165356 11780 gomacc_common.cc:166] failed to connect to: C:\Users\ZWX953~1\AppData\Local\Temp\goma\goma.ipc: 10061
E0831 14:44:30.166384 11780 goma_ipc.cc:71] call failed: Failed to connect to C:\Users\ZWX953~1\AppData\Local\Temp\goma\goma.ipc
GOMA: port request failed. connect_success: 0, err: -1 Failed to connect to C:\Users\ZWX953~1\AppData\Local\Temp\goma\goma.ipc, http_return_code: 0
E0831 14:45:50.312211 12256 gomacc_common.cc:166] failed to connect to: C:\Users\ZWX953~1\AppData\Local\Temp\goma\goma.ipc: 10061
E0831 14:45:50.313288 12256 goma_ipc.cc:71] call failed: Failed to connect to C:\Users\ZWX953~1\AppData\Local\Temp\goma\goma.ipc
GOMA: port request failed. connect_success: 0, err: -1 Failed to connect to C:\Users\ZWX953~1\AppData\Local\Temp\goma\goma.ipc, http_return_code: 0
E0831 14:47:10.508966 14292 gomacc_common.cc:166] failed to connect to: C:\Users\ZWX953~1\AppData\Local\Temp\goma\goma.ipc: 10061
E0831 14:47:10.508966 14292 goma_ipc.cc:71] call failed: Failed to connect to C:\Users\ZWX953~1\AppData\Local\Temp\goma\goma.ipc
GOMA: port request failed. connect_success: 0, err: -1 Failed to connect to C:\Users\ZWX953~1\AppData\Local\Temp\goma\goma.ipc, http_return_code: 0
Traceback (most recent call last):
  File "goma_ctl.py", line 3194, in <module>
    sys.exit(main())
  File "goma_ctl.py", line 3189, in main
    goma.Dispatch(sys.argv[1:])
  File "goma_ctl.py", line 1434, in Dispatch
    self._action_mappings.get(args[0], self._DefaultAction)()
  File "goma_ctl.py", line 808, in _EnsureStartCompilerProxy
    self._GenericStartCompilerProxy(ensure=True, force_update=False)
  File "goma_ctl.py", line 767, in _GenericStartCompilerProxy
    self._env.ExecCompilerProxy()
  File "goma_ctl.py", line 2117, in ExecCompilerProxy
    return self._GetCompilerProxyPort(proc=proc)  # set the new gomacc_port.
  File "goma_ctl.py", line 1677, in _GetCompilerProxyPort
    raise e
__main__.Error: compiler_proxy is not ready? pid=12416

    at checkExecSyncError (child_process.js:621:11)
    at Object.execFileSync (child_process.js:639:15)
    at Object.ensureGomaStart [as ensure] (D:\electron\0827\000\build-tools-master\src\utils\goma.js:129:16)
    at runNinja (D:\electron\0827\000\build-tools-master\src\e-build.js:63:10)
    at Object.<anonymous> (D:\electron\0827\000\build-tools-master\src\e-build.js:132:3)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10)

**Comment by MarshallOfSound** [comment]
Duplicate #168
