### ISSUE TITLE
How to prepare compiler_proxy?

### ISSUE THREAD

**Issue by AlvinZhangH** [electron/build-tools#168]
Traceback (most recent call last):
  File "goma_ctl.py", line 3194, in <module>
    sys.exit(main())
  File "goma_ctl.py", line 3189, in main
    goma.Dispatch(sys.argv[1:])
  File "goma_ctl.py", line 1434, in Dispatch
    self._action_mappings.get(args[0], self._DefaultAction)()
  File "goma_ctl.py", line 808, in _EnsureStartCompilerProxy
    self._GenericStartCompilerProxy(ensure=True, force_update=False)
  File "goma_ctl.py", line 767, in _GenericStartCompilerProxy
    self._env.ExecCompilerProxy()
  File "goma_ctl.py", line 2117, in ExecCompilerProxy
    return self._GetCompilerProxyPort(proc=proc)  # set the new gomacc_port.
  File "goma_ctl.py", line 1677, in _GetCompilerProxyPort
    raise e
__main__.Error: compiler_proxy is not ready? pid=9888

**Comment by MarshallOfSound** [comment]
`e build` will start the compile proxy (or at least try to) you can try disabling goma by setting `goma` to `false` in your config
