### ISSUE TITLE
e build error: missing and no known rule to make it

### ISSUE THREAD

**Issue by epubcn** [electron/build-tools#234]
After e init & e sync，I met the following error when I trying to execute e build --no-goma, anyone can help me? Thx a lot.

```
D:\Electron\electron\src\electron>e build --gen
Running "C:\Users\Administrator\.electron_build_tools\third_party\depot_tools\gn.bat gen out/Release --args=import("//electron/build/args/release.gn") import("C:\Users\Administrator\.electron_build_tools\third_party\goma.gn")" in D:\Electron\electron\src
Done. Made 15760 targets from 2631 files in 13532ms
Running "ninja -j 200 electron" in D:\Electron\electron\src\out\Release
ninja: error: '../../electron/node_modules/@primer/octicons/build/build.css', needed by 'gen/electron/js/default_app/electron/default_app/octicon/build.css', missing and no known rule to make it
ERROR Error: Command failed: ninja -j 200 electron
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:15)
    at Object.depotExecFileSync [as execFileSync] (C:\Users\Administrator\.electron_build_tools\src\utils\depot-tools.js:106:16)
    at runNinja (C:\Users\Administrator\.electron_build_tools\src\e-build.js:78:9)
    at Object.<anonymous> (C:\Users\Administrator\.electron_build_tools\src\e-build.js:136:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
```

**Comment by epubcn** [comment]
OK, I solved the issue by this command: `npm config set -g production false`
then execute `npm install` on electron path,  all dependencies will be installed
but after that, when I try e build again, I met another error:
**************************************************************
Not logged in. Run this command and retry the build:
    pushd %GOMACLIENTDIR% && vpython goma_auth.py login && popd
**************************************************************

oh my god
