### ISSUE TITLE
Can't init an environment named "test"

### ISSUE THREAD

**Issue by itsananderson** [electron/build-tools#237]
When I try to initialize an environment named "test", I get the following error:

```
e init --root ~/electron/test test
INFO Root /Users/will/electron/test already exists.
INFO (OK if you are sharing $root between multiple build configs)
New build config test created in /Users/will/.electron_build_tools/configs/evm.test.json
Now using config test
Running "e load-xcode --quiet"
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/will/electron/test/src/electron/.circleci/config.yml'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at expectedXcodeVersion (/Users/will/.electron_build_tools/src/utils/xcode.js:63:42)
    at Object.ensureXcode (/Users/will/.electron_build_tools/src/utils/xcode.js:99:20)
    at Object.<anonymous> (/Users/will/.electron_build_tools/src/e-load-xcode.js:15:7)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/will/electron/test/src/electron/.circleci/config.yml'
}
ERROR Error: Command failed: /usr/local/Cellar/node/13.7.0/bin/node /Users/will/.electron_build_tools/src/e build node:headers
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:15)
    at ensureNodeHeaders (/Users/will/.electron_build_tools/src/utils/headers.js:28:18)
    at Object.<anonymous> (/Users/will/.electron_build_tools/src/e-test.js:62:3)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
ERROR Error: Command failed: /usr/local/Cellar/node/13.7.0/bin/node /Users/will/.electron_build_tools/src/e use test
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:15)
    at Object.<anonymous> (/Users/will/.electron_build_tools/src/e-init.js:197:16)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

I *think* this is due to some argument parsing issue where build-tools is mistakingly trying to kick off an `e test` task, but that doesn't work because the environment hasn't been synced.

Running `e use test` also produces part of the error:

```
e use test
Now using config test
Running "e load-xcode --quiet"
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/will/electron/test/src/electron/.circleci/config.yml'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at expectedXcodeVersion (/Users/will/.electron_build_tools/src/utils/xcode.js:63:42)
    at Object.ensureXcode (/Users/will/.electron_build_tools/src/utils/xcode.js:99:20)
    at Object.<anonymous> (/Users/will/.electron_build_tools/src/e-load-xcode.js:15:7)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/will/electron/test/src/electron/.circleci/config.yml'
}
ERROR Error: Command failed: /usr/local/Cellar/node/13.7.0/bin/node /Users/will/.electron_build_tools/src/e build node:headers
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:15)
    at ensureNodeHeaders (/Users/will/.electron_build_tools/src/utils/headers.js:28:18)
    at Object.<anonymous> (/Users/will/.electron_build_tools/src/e-test.js:62:3)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

The error doesn't happen if I call the project `testing` instead of `test`.

**Comment by dsanders11** [comment]
It looks like this no longer happens, at least in my testing. @codebytere, could you confirm it's doesn't repro for you and then close the issue if so?
