### ISSUE TITLE
Error attempting to build v10.1.6 on Mac OS.

### ISSUE THREAD

**Issue by whatbotisthis** [electron/build-tools#243]
I'm able to build v13 nightly without any problems. However when I try to build v10.1.6 I get errors on Mac OS Catalina. I'm assuming there's a step I'm missing but I can't seem to find any info on how to build older versions.

The initial sync goes just fine and from here I can build latest. But then I cd into electron and do `git checkout tags/v10.1.6` which works and then I attempt to `e sync` again which takes hours before giving the following error:

```
________ running 'git -c core.deltaBaseCacheLimit=2g fetch origin 85.0.4183.121 --verbose' in '/Users/me/electron-test/electron/src' attempt 4 / 4

[10:56:55] fatal: couldn't find remote ref 85.0.4183.121
[10:56:55] fatal: the remote end hung up unexpectedly
----------------------------------------
Error: Command 'git -c core.deltaBaseCacheLimit=2g fetch origin 85.0.4183.121 --verbose' returned non-zero exit status 128 in /Users/me/electron-test/electron/src
ERROR Error: Command failed: python /Users/me/.electron_build_tools/third_party/depot_tools/gclient.py sync --with_branch_heads --with_tags -vv
at checkExecSyncError (child_process.js:611:11)
at Object.execFileSync (child_process.js:629:15)
at Object.depotExecFileSync [as execFileSync] (/Users/me/.electron_build_tools/src/utils/depot-tools.js:117:16)
at runGClientSync (/Users/me/.electron_build_tools/src/e-sync.js:54:9)
at Object.<anonymous> (/Users/me/.electron_build_tools/src/e-sync.js:76:3)
at Module._compile (internal/modules/cjs/loader.js:1147:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
at Module.load (internal/modules/cjs/loader.js:996:32)
at Function.Module._load (internal/modules/cjs/loader.js:896:14)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
```

**Comment by marcello3d** [comment]
I'm hitting this same error while trying to build electron 11.0.4 on macos catalina, following pretty much the same steps as outlined above.

```
[0:04:51] fetch +refs/branch-heads/*:refs/branch-heads/* took 0.7 minutes
[0:04:51] Fetching +refs/tags/*:refs/tags/*
[0:04:51] running "git fetch -v --progress --prune origin +refs/tags/*:refs/tags/*" in "/Users/marcello/.git_cache/chromium.googlesource.com-chromium-src"
[0:05:33] POST git-upload-pack (gzip 418098 to 207329 bytes)
[0:15:37] error: RPC failed; HTTP 499 curl 22 The requested URL returned error: 499 
[0:15:37] fatal: The remote end hung up unexpectedly
[0:16:17] POST git-upload-pack (gzip 418098 to 207329 bytes)
[0:26:27] error: RPC failed; HTTP 499 curl 22 The requested URL returned error: 499 
[0:26:27] fatal: The remote end hung up unexpectedly
[0:27:08] POST git-upload-pack (gzip 418098 to 207329 bytes)
[0:37:11] error: RPC failed; HTTP 499 curl 22 The requested URL returned error: 499 
[0:37:11] fatal: The remote end hung up unexpectedly
[0:37:49] POST git-upload-pack (gzip 418098 to 207329 bytes)
[0:47:56] error: RPC failed; HTTP 499 curl 22 The requested URL returned error: 499 
[0:47:56] fatal: The remote end hung up unexpectedly
[0:48:00] fetch +refs/tags/*:refs/tags/* took 43.2 minutes
[0:48:00] Finished running: git config remote.origin.url
[0:48:00] Finished running: git rev-list -n 1 HEAD
[0:48:00] Finished running: git rev-parse --abbrev-ref=strict HEAD
[0:48:02] 
________ running 'git -c core.deltaBaseCacheLimit=2g fetch origin --verbose' in '/Users/marcello/Documents/electron/src'

[0:48:02] From /Users/marcello/.git_cache/chromium.googlesource.com-chromium-src

……snip……

[0:48:05] Fetching origin
[0:48:06] 
________ running 'git -c core.deltaBaseCacheLimit=2g fetch origin 87.0.4280.67 --verbose' in '/Users/marcello/Documents/electron/src'

[0:48:06] fatal: Couldn't find remote ref 87.0.4280.67
[0:48:06] fatal: The remote end hung up unexpectedly
[0:48:06] 
________ running 'git -c core.deltaBaseCacheLimit=2g fetch origin 87.0.4280.67 --verbose' in '/Users/marcello/Documents/electron/src' attempt 2 / 4

[0:48:06] fatal: Couldn't find remote ref 87.0.4280.67
[0:48:06] fatal: The remote end hung up unexpectedly
[0:48:08] 
________ running 'git -c core.deltaBaseCacheLimit=2g fetch origin 87.0.4280.67 --verbose' in '/Users/marcello/Documents/electron/src' attempt 3 / 4

[0:48:08] fatal: Couldn't find remote ref 87.0.4280.67
[0:48:08] fatal: The remote end hung up unexpectedly
[0:48:10] 
________ running 'git -c core.deltaBaseCacheLimit=2g fetch origin 87.0.4280.67 --verbose' in '/Users/marcello/Documents/electron/src' attempt 4 / 4

[0:48:10] fatal: Couldn't find remote ref 87.0.4280.67
[0:48:10] fatal: The remote end hung up unexpectedly
----------------------------------------
Error: Command 'git -c core.deltaBaseCacheLimit=2g fetch origin 87.0.4280.67 --verbose' returned non-zero exit status 128 in /Users/marcello/Documents/electron/src
ERROR Error: Command failed: python /Users/marcello/.electron_build_tools/third_party/depot_tools/gclient.py sync --with_branch_heads --with_tags -vv -v -v
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:15)
    at Object.depotExecFileSync [as execFileSync] (/Users/marcello/.electron_build_tools/src/utils/depot-tools.js:117:16)
    at runGClientSync (/Users/marcello/.electron_build_tools/src/e-sync.js:54:9)
    at Object.<anonymous> (/Users/marcello/.electron_build_tools/src/e-sync.js:76:3)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
```

**Comment by marcello3d** [comment]
Happens on v11.1.1 tag as well

**Comment by codebytere** [comment]
Typically this happens as a result of git/https buffer settings - try `git config http.postBuffer 524288000` and run again.
