### ISSUE TITLE
Spawning vpython results in ENOENT on Windows

### ISSUE THREAD

**Issue by rzhao271** [electron/build-tools#261]
Even though `vpython` is in my `process.env.Path`, it isn't found until I pass in `shell: true` on Windows.
I attached an example screenshot in git bash, but the same error occurs using cmd.

<img src="https://user-images.githubusercontent.com/7199958/110144782-9181dd80-7d8d-11eb-8cea-0cc1c6badb63.PNG" alt="Screenshot of git bash terminal showing the issue described above" height="600px">

**Comment by rconde01** [comment]
I have the same issue, but unless I messed something up, applying the changes in that PR didn't fix it:

```
C:\Users\ContainerAdministrator\.electron_build_tools\src>e build electron:dist
Running "goma_ctl.py ensure_start" in C:\Users\ContainerAdministrator\.electron_build_tools\third_party\goma
ERROR Error: Command failed: C:\Windows\system32\cmd.exe /d /s /c "vpython goma_ctl.py ensure_start"
'vpython' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (node:child_process:690:11)
    at Object.execFileSync (node:child_process:709:15)
    at Object.ensureGomaStart [as ensure] (C:\Users\ContainerAdministrator\.electron_build_tools\src\utils\goma.js:175:16)
    at runNinja (C:\Users\ContainerAdministrator\.electron_build_tools\src\e-build.js:60:10)
    at Object.<anonymous> (C:\Users\ContainerAdministrator\.electron_build_tools\src\e-build.js:133:3)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
```

**Comment by rzhao271** [comment]
I'm using cmd and I get the following results

```
C:\Users\raymondzhao>which vpython
/c/Users/raymondzhao/Documents/depot_tools/vpython

C:\Users\raymondzhao>where vpython
C:\Users\raymondzhao\Documents\depot_tools\vpython
C:\Users\raymondzhao\Documents\depot_tools\vpython.bat
```

Where my `depot_tools` were from manually setting up the build for Chromium https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md#install
Wondering if it's the same for you?

**Comment by rconde01** [comment]
I have not set up depot_tools separately, but am just pulling them in via electron build-tools. With your update merged i get:

```
Writing new goma.gn file C:\Users\ContainerAdministrator\.electron_build_tools\third_party\goma.gn
Downloading "https://electron-build-tools.s3-us-west-2.amazonaws.com/build-dependencies/064e0beb3c11b82b66ae4b4959e6c0cdaa2116d77c50841e4a213d4f4fb1aeaf/goma-win.zip" into C:\Users\ContainerAdministrator\.electron_build_tools\third_party\goma-win.zip
[=======================================================================================================================================================================================================] 9266800/bps 100% 0.0s 
Running "goma_ctl.py ensure_start" in C:\Users\ContainerAdministrator\.electron_build_tools\third_party\goma
ERROR Error: Command failed: C:\Windows\system32\cmd.exe /d /s /c "vpython goma_ctl.py ensure_start"
'vpython' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (node:child_process:690:11)
    at Object.execFileSync (node:child_process:709:15)
    at Object.ensureGomaStart [as ensure] (C:\Users\ContainerAdministrator\.electron_build_tools\src\utils\goma.js:175:16)
    at runNinja (C:\Users\ContainerAdministrator\.electron_build_tools\src\e-build.js:60:10)
    at Object.<anonymous> (C:\Users\ContainerAdministrator\.electron_build_tools\src\e-build.js:133:3)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
```
If I do `where vpython` i get:
```
C:\>where vpython
INFO: Could not find files for the given pattern(s).
```

If I fix up my path like:
```
set PATH=C:\electron\src\third_party\depot_tools;%PATH%
```
and do `where vpython` I get:
```
C:\electron>where vpython
C:\electron\src\third_party\depot_tools\vpython
C:\electron\src\third_party\depot_tools\vpython.bat
```
but...I still get the same error.

Here's the docker file i'm using:
```
FROM mcr.microsoft.com/windows:2004

ENV chocolateyUseWindowsCompression false

RUN powershell -Command Set-ExecutionPolicy Unrestricted -Force
RUN powershell -Command \
    iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1')); \
    choco feature disable --name showDownloadProgress

RUN choco install -y -d --accept-license git
RUN git config --system core.longpaths true

RUN choco install -y -d --accept-license nodejs
RUN choco install -y -d --accept-license vim

# chrome build needs python2...eww
RUN choco install -y -d --accept-license python2
RUN pip install pywin32
RUN pip install crcmod

# https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md#visual-studio
RUN choco install -y -d --accept-license visualstudio2019community \
    --package-parameters \
    "--add Microsoft.VisualStudio.Workload.NativeDesktop --add Microsoft.VisualStudio.Component.VC.ATLMFC --includeRecommended --passive"

# https://github.com/electron/build-tools
RUN npm install --global yarn
RUN npm i -g @electron/build-tools

# Setup required git settings for electron build tools
# If you don't set these the e init will fail
RUN git config --global core.filemode false
RUN git config --global core.autocrlf false
RUN git config --global branch.autosetuprebase always

RUN e init --root=C:/electron release
RUN e sync -vvvv

CMD [ "cmd" ]
```

Seems like the issue needs to be reopened?

**Comment by rzhao271** [comment]
The commit got reverted because it broke the main repo's CI apparently. See https://github.com/electron/electron/pull/28053 and https://github.com/electron/build-tools/commit/4895bfd81c000b22c9dde9c13aae6de8cf7e6a05
@codebytere or @jkleinsc can https://github.com/electron/build-tools/commit/493cff590252c6881de67bf6f866a8cd544943c5 and https://github.com/electron/build-tools/commit/5798b867bc174c7ef96ef1cacde0f3f4033c9b0f also be reverted (in that order)? It seems that it's too easy to break various Windows setups by trying to change exactly how the goma files are called.
I also have a feeling that the original settings weren't working for me due to my VS Code specific setup, rather than something to do with the scripts.

**Comment by rconde01** [comment]
I guess I’ll open a new issue...don’t know what the process is here.
