### ISSUE TITLE
init failing on windows

### ISSUE THREAD

**Issue by louistb** [electron/build-tools#272]
Hi, i am trying to setup build-tools and im having issues with pywin32.

if i run e init im getting : 

```
--> A required dependency "pywin32" could not be located, it probably has to be installed.
Do you want build-tools to try fix this for you? [y/n]: y

Running "choco install pywin32 --yes"
ERROR Error: Failed to run "choco install pywin32 --yes"
    at spawnSyncWithLog (C:\Users\LouisTB\.electron_build_tools\src\utils\deps-check.js:11:11)
    at fix (C:\Users\LouisTB\.electron_build_tools\src\utils\deps-check.js:39:9)
    at maybeAutoFix (C:\Users\LouisTB\.electron_build_tools\src\utils\maybe-auto-fix.js:13:3)
    at whichAndFix (C:\Users\LouisTB\.electron_build_tools\src\utils\which.js:10:5)
    at checkPlatformDependencies (C:\Users\LouisTB\.electron_build_tools\src\utils\deps-check.js:61:7)
    at Object.<anonymous> (C:\Users\LouisTB\.electron_build_tools\src\e-init.js:163:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```
    
   If i try to install pywin32 with pip i can install properly but then when  i run init i get : 

```
WARN A fixable error has occurred
--> A required dependency "pywin32" could not be located, it probably has to be installed.
Do you want build-tools to try fix this for you? [y/n]: n
ERROR Error: A required dependency "pywin32" could not be located, it probably has to be installed.
    at whichAndFix (C:\Users\LouisTB\.electron_build_tools\src\utils\which.js:12:7)
    at checkPlatformDependencies (C:\Users\LouisTB\.electron_build_tools\src\utils\deps-check.js:61:7)
    at Object.<anonymous> (C:\Users\LouisTB\.electron_build_tools\src\e-init.js:163:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

How could i fix this ? Thanks

**Comment by louistb** [comment]
fixed it by removing all python version and then running e init again it reinstalled all needed package using choco
