### ISSUE TITLE
Windows toolchain out of date or doesn't exist, updating (Pro) error on e sync

### ISSUE THREAD

**Issue by NSBCypher** [electron/build-tools#293]
```Done in 1.31s.
________ running 'python3 src/build/landmines.py' in 'C:\Users\c\Desktop\r\electron'
________ running 'python3 src/third_party/depot_tools/update_depot_tools_toggle.py --disable' in 'C:\Users\c\Desktop\r\electron'
________ running 'python3 src/tools/remove_stale_pyc_files.py src/android_webview/tools src/build/android src/gpu/gles2_conform_support src/infra src/ppapi src/printing src/third_party/blink/renderer/build/scripts src/third_party/blink/tools src/third_party/catapult src/tools' in 'C:\Users\c\Desktop\r\electron'
________ running 'python3 src/build/vs_toolchain.py update --force' in 'C:\Users\c\Desktop\r\electron'
Windows toolchain out of date or doesn't exist, updating (Pro)...
  current_hashes:
  desired_hash: e146e01913
Traceback (most recent call last):
  File "C:\Users\c\Desktop\r\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 608, in <module>
    sys.exit(main())
  File "C:\Users\c\Desktop\r\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 547, in main
    DoTreeMirror(toolchain_target_dir, args.desired_hash)
  File "C:\Users\c\Desktop\r\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 363, in DoTreeMirror
    temp_dir, local_zip = DownloadUsingHttp(tree_sha1 + '.zip')
  File "C:\Users\c\Desktop\r\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 313, in DownloadUsingHttp
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
Traceback (most recent call last):
  File "src/build/vs_toolchain.py", line 573, in <module>
    sys.exit(main())
  File "src/build/vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "src/build/vs_toolchain.py", line 517, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Users\c\.electron_build_tools\third_party\depot_tools\bootstrap-2@3_8_10_chromium_19_bin\python3\bin\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\c\\.electron_build_tools\\third_party\\depot_tools\\bootstrap-2@3_8_10_chromium_19_bin\\python3\\bin\\python3.exe', 'C:\\Users\\c\\Desktop\\r\\electron\\src\\third_party\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'C:\\Users\\c\\Desktop\\r\\electron\\src\\build\\win_toolchain.json', 'e146e01913', '--force']' returned non-zero exit status 1.
Error: Command 'python3 src/build/vs_toolchain.py update --force' returned non-zero exit status 1 in C:\Users\c\Desktop\r\electron
Windows toolchain out of date or doesn't exist, updating (Pro)...
  current_hashes:
  desired_hash: e146e01913
Traceback (most recent call last):
  File "C:\Users\c\Desktop\r\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 608, in <module>
    sys.exit(main())
  File "C:\Users\c\Desktop\r\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 547, in main
    DoTreeMirror(toolchain_target_dir, args.desired_hash)
  File "C:\Users\c\Desktop\r\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 363, in DoTreeMirror
    temp_dir, local_zip = DownloadUsingHttp(tree_sha1 + '.zip')
  File "C:\Users\c\Desktop\r\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 313, in DownloadUsingHttp
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
Traceback (most recent call last):
  File "src/build/vs_toolchain.py", line 573, in <module>
    sys.exit(main())
  File "src/build/vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "src/build/vs_toolchain.py", line 517, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Users\c\.electron_build_tools\third_party\depot_tools\bootstrap-2@3_8_10_chromium_19_bin\python3\bin\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\c\\.electron_build_tools\\third_party\\depot_tools\\bootstrap-2@3_8_10_chromium_19_bin\\python3\\bin\\python3.exe', 'C:\\Users\\c\\Desktop\\r\\electron\\src\\third_party\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'C:\\Users\\c\\Desktop\\r\\electron\\src\\build\\win_toolchain.json', 'e146e01913', '--force']' returned non-zero exit status 1.

ERROR Error: Command failed: python C:\Users\c\.electron_build_tools\third_party\depot_tools\gclient.py sync --with_branch_heads --with_tags -vv
    at checkExecSyncError (child_process.js:643:11)
    at Object.execFileSync (child_process.js:661:15)
    at Object.depotExecFileSync [as execFileSync] (C:\Users\c\.electron_build_tools\src\utils\depot-tools.js:118:16)
    at runGClientSync (C:\Users\c\.electron_build_tools\src\e-sync.js:54:9)
    at Object.<anonymous> (C:\Users\c\.electron_build_tools\src\e-sync.js:76:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
```

Hi, I am getting the above error when running `e sync`.

Anyone facing the same issue or can suggest a solution?

I am sure I have all the prerequisites installed. I tried a fresh installation following all the instructions from scratch on two different machines already.

**Comment by aarock1234** [comment]
I am facing this exact same error:

[err.txt](https://github.com/electron/build-tools/files/6681517/err.txt)

**Comment by aarock1234** [comment]
I am having the same issue:

```
Applying: fix: -Wincompatible-pointer-types-discards-qualifiers error
Applying: fix: add v8_enable_reverse_jsargs defines in common.gypi
Applying: fix: allow preventing InitializeInspector in env
Applying: src: allow embedders to provide a custom PageAllocator to NodePlatform
Applying: fix crypto tests to run with bssl
Applying: fix: handle new ToString() behavior in v8 serdes test
Applying: src: remove extra semis from member fns
Applying: src: add NODE_USE_V8_PLATFORM in InitializeOncePerProcess
Applying: tls: tweak clientCertEngine argument parsing
Applying: src: add get/set pair for unhandled rejections mode
Applying: fix: account for debugger agent race condition
Applying: build: add GN config
Applying: fix: ensure that self is retained until the RACSignal is complete
Applying: Remove MTLManagedObjectAdapter.h
Applying: build: conditionally import EXT headers from framework or from relative path
Hook 'python3 src/electron/script/apply_all_patches.py src/electron/patches/config.json' took 361.42 secs
________ running 'python3 src/electron/script/patches-mtime-cache.py apply --cache-file src/electron/patches/mtime-cache.json' in 'C:\Users\A\Desktop\storme 1.0\electron\electron'
________ running 'python3 -c import os, subprocess; os.chdir(os.path.join("src", "electron")); subprocess.check_call(["python3", "script/lib/npx.py", "yarn@1.15.2", "install", "--frozen-lockfile"]);' in 'C:\Users\A\Desktop\storme 1.0\electron\electron'
yarn install v1.15.2
$ node -e 'process.exit(0)'
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-config-standard@14.1.1" has unmet peer dependency "eslint-plugin-promise@>=4.2.1".
[4/4] Building fresh packages...
$ husky install
husky - Git hooks installed
Done in 40.72s.
Hook 'python3 -c 'import os, subprocess; os.chdir(os.path.join("src", "electron")); subprocess.check_call(["python3", "script/lib/npx.py", "yarn@1.15.2", "install", "--frozen-lockfile"]);'' took 43.08 secs
________ running 'python3 src/build/landmines.py' in 'C:\Users\A\Desktop\storme 1.0\electron\electron'
________ running 'python3 src/third_party/depot_tools/update_depot_tools_toggle.py --disable' in 'C:\Users\A\Desktop\storme 1.0\electron\electron'
________ running 'python3 src/tools/remove_stale_pyc_files.py src/android_webview/tools src/build/android src/gpu/gles2_conform_support src/infra src/ppapi src/printing src/third_party/blink/renderer/build/scripts src/third_party/blink/tools src/third_party/catapult src/tools' in 'C:\Users\A\Desktop\storme 1.0\electron\electron'
________ running 'python3 src/build/vs_toolchain.py update --force' in 'C:\Users\A\Desktop\storme 1.0\electron\electron'
Windows toolchain out of date or doesn't exist, updating (Pro)...
  current_hashes:
  desired_hash: e146e01913
Traceback (most recent call last):
  File "C:\Users\A\Desktop\storme 1.0\electron\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 608, in <module>
    sys.exit(main())
  File "C:\Users\A\Desktop\storme 1.0\electron\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 547, in main
    DoTreeMirror(toolchain_target_dir, args.desired_hash)
  File "C:\Users\A\Desktop\storme 1.0\electron\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 363, in DoTreeMirror
    temp_dir, local_zip = DownloadUsingHttp(tree_sha1 + '.zip')
  File "C:\Users\A\Desktop\storme 1.0\electron\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 313, in DownloadUsingHttp
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
Traceback (most recent call last):
  File "src/build/vs_toolchain.py", line 573, in <module>
    sys.exit(main())
  File "src/build/vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "src/build/vs_toolchain.py", line 517, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Users\A\.electron_build_tools\third_party\depot_tools\bootstrap-2@3_8_10_chromium_19_bin\python3\bin\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\A\\.electron_build_tools\\third_party\\depot_tools\\bootstrap-2@3_8_10_chromium_19_bin\\python3\\bin\\python3.exe', 'C:\\Users\\A\\Desktop\\storme 1.0\\electron\\electron\\src\\third_party\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'C:\\Users\\A\\Desktop\\storme 1.0\\electron\\electron\\src\\build\\win_toolchain.json', 'e146e01913', '--force']' returned non-zero exit status 1.
Error: Command 'python3 src/build/vs_toolchain.py update --force' returned non-zero exit status 1 in C:\Users\A\Desktop\storme 1.0\electron\electron
Windows toolchain out of date or doesn't exist, updating (Pro)...
  current_hashes:
  desired_hash: e146e01913
Traceback (most recent call last):
  File "C:\Users\A\Desktop\storme 1.0\electron\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 608, in <module>
    sys.exit(main())
  File "C:\Users\A\Desktop\storme 1.0\electron\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 547, in main
    DoTreeMirror(toolchain_target_dir, args.desired_hash)
  File "C:\Users\A\Desktop\storme 1.0\electron\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 363, in DoTreeMirror
    temp_dir, local_zip = DownloadUsingHttp(tree_sha1 + '.zip')
  File "C:\Users\A\Desktop\storme 1.0\electron\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 313, in DownloadUsingHttp
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
Traceback (most recent call last):
  File "src/build/vs_toolchain.py", line 573, in <module>
    sys.exit(main())
  File "src/build/vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "src/build/vs_toolchain.py", line 517, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Users\A\.electron_build_tools\third_party\depot_tools\bootstrap-2@3_8_10_chromium_19_bin\python3\bin\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\A\\.electron_build_tools\\third_party\\depot_tools\\bootstrap-2@3_8_10_chromium_19_bin\\python3\\bin\\python3.exe', 'C:\\Users\\A\\Desktop\\storme 1.0\\electron\\electron\\src\\third_party\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'C:\\Users\\A\\Desktop\\storme 1.0\\electron\\electron\\src\\build\\win_toolchain.json', 'e146e01913', '--force']' returned non-zero exit status 1.

ERROR Error: Command failed: python C:\Users\A\.electron_build_tools\third_party\depot_tools\gclient.py sync --with_branch_heads --with_tags -vv
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:15)
    at Object.depotExecFileSync [as execFileSync] (C:\Users\A\.electron_build_tools\src\utils\depot-tools.js:118:16)
    at runGClientSync (C:\Users\A\.electron_build_tools\src\e-sync.js:54:9)
    at Object.<anonymous> (C:\Users\A\.electron_build_tools\src\e-sync.js:76:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)```
    
OS Name: Microsoft Windows 10 Pro
Version: 10.0.19042 Build 19042

**Comment by k3ru-sailco** [comment]
Hello, I am also experiencing this issue. :(

**Comment by ChrisPei** [comment]
same issue :(

**Comment by ChrisPei** [comment]
I found the solution.

Check out your evn file at `%USERPROFILE%\.electron_build_tools\configs\evm.xxxx.json`

```
...
  "env": {
    "CHROMIUM_BUILDTOOLS_PATH": ".......",
    "GIT_CACHE_PATH": ".........",
    "DEPOT_TOOLS_WIN_TOOLCHAIN": 0 # <--  + Add this line!!!
  }
...
```

`Also, add a DEPOT_TOOLS_WIN_TOOLCHAIN system variable in the same way, and set it to 0. This tells depot_tools to use your locally installed version of Visual Studio (by default, depot_tools will try to use a google-internal version).`

[chromium windows_build_instructions](https://github.com/chromium/chromium/blob/master/docs/windows_build_instructions.md#install-depot_tools)

**Comment by MarshallOfSound** [comment]
@ChrisPei That's not the right solution here, we do explicitly want the toolchain.  Electron just hasn't published the most recent one yet, we're working on it.  Hopefully we'll have this updated tomorrow

**Comment by ChrisPei** [comment]
@MarshallOfSound Yes, you are right. I have also tried to modify the get_toolchain_if_necessary.py file to fix the `ModuleNotFoundError: No module named 'urlparse'` error. But that need to create a new git repo dependency, otherwise it will be replaced by current repo when I run `e sync`. 😂
Looking forward to your next updates

**Comment by not-the-car** [comment]
Hi @MarshallOfSound any chance of a workaround in the meantime?

**Comment by martinsXXX** [comment]
We are stuck with the same problem and would appreciate a solution, too. Thank you!

**Comment by arbaaz** [comment]
> ModuleNotFoundError: No module named 'urlparse'
Got this error and adding DEPOT_TOOLS_WIN_TOOLCHAIN to evm.xxx.json fixed it.

**Comment by martinsXXX** [comment]
Can you please explain more excactly, how  to add this? Set it to which value? 
https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/windows_build_instructions.md#visual-studio
says, "Also, add a DEPOT_TOOLS_WIN_TOOLCHAIN system variable in the same way, and set it to 0. "
I'm confused...

**Comment by arbaaz** [comment]
@martinsXXX Start Visual Studio Installer and Select "Desktop development with C++" from the options.

Add DEPOT_TOOLS_WIN_TOOLCHAIN to System Env:

Control Panel → System and Security → System → Advanced system settings

**Comment by martinsXXX** [comment]
.. I have set this system env variable already to value 0 as mentioned in https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/windows_build_instructions.md#visual-studio
But you wrote it should be added to evm.XXX.json and how to do this, was my question
Thank you

i. A. Martin Schoellhammer
Softwareentwicklung
Softwareentwickler
Phone +49(0)7142/705-175<callto:+49(0)7142/705-175>
Fax +49(0)7142705500<callto:+49(0)7142705500>
***@***.******@***.***>

[cid:Logos_Signatur_DD_EN_1a82443c-b03a-407b-9400-e9992e51e2f5.png]

DÜRR DENTAL SE
Höpfigheimer Str. 17
74321 Bietigheim-Bissingen
Deutschland / Germany
Phone +49 (0) 7142 / 705 0<tel:+4971427050>
Fax +49 (0) 7142 / 705 500<fax:+497142705500>
www.duerrdental.com<http://www.duerrdental.com>
Join us on Facebook www.facebook.com/DuerrDental<http://www.facebook.com/DuerrDental>

Firmensitz / Registered Office: Höpfigheimer Str. 17, 74321 Bietigheim-Bissingen Handelsregister / Register of Commerce: Amtsgericht Stuttgart HRB 763587

Vorstand / Executive Board: Martin Dürrstein (Vorsitzender / CEO), Stefan Pfanzelt, Christian Schorndorfer
Vorsitzender des Aufsichtsrates / Chairman of the Supervisory Board: Bernhard Oberschmidt


[cid:Footer_e-mail-Signatur_80yearsDD_e8ef2f01-133d-4a9c-a7c2-7dcea1c6ea88.png]<https://80.duerrdental.com/en/?utm_source=signatur&utm_medium=email&utm_campaign=80jahre>
<https://www.duerrdental.com/en/products/promotions/best-protection-for-practice-team-and-patient/?utm_source=signatur&utm_medium=email&utm_campaign=best-protection>
Discover 80 years of colourful variety!<https://80.duerrdental.com/en/?utm_source=signatur&utm_medium=email&utm_campaign=80jahre>
Von: Arbaaz ***@***.***>
Gesendet: Donnerstag, 8. Juli 2021 07:06
An: electron/build-tools ***@***.***>
Cc: Schoellhammer, Martin ***@***.***>; Mention ***@***.***>
Betreff: Re: [electron/build-tools] Windows toolchain out of date or doesn't exist, updating (Pro) error on e sync (#293)


@martinsXXX<https://github.com/martinsXXX> Start Visual Studio Installer and Select "Desktop development with C++" from the options.

Add DEPOT_TOOLS_WIN_TOOLCHAIN to System Env:

Control Panel → System and Security → System → Advanced system settings

**Comment by arbaaz** [comment]
evm.xxx.json file will be in this directory.
C:\Users\<user_name>\.electron_build_tools\configs

**Comment by martinsXXX** [comment]
MarshallofSound said 9 days ago "that's not the right solution here ...." when someone suggested DEPOT_TOOLS_WIN_TOOLCHAIN": 0 # <--  + Add this line!!!
Anyway, arbaaz's suggestion didn't work for me. 
So I'm still stuck

**Comment by samuelmaddock** [comment]
This seems to have something to do with changes to python3 libs. The code should look something like the following:
```diff
diff --git a/win_toolchain/get_toolchain_if_necessary.py b/win_toolchain/get_toolchain_if_necessary.py
index b6c479ed..17b69e1f 100755
--- a/win_toolchain/get_toolchain_if_necessary.py
+++ b/win_toolchain/get_toolchain_if_necessary.py
@@ -310,19 +310,20 @@ def DelayBeforeRemoving(target_dir):
 def DownloadUsingHttp(filename):
   """Downloads the given file from a url defined in
      DEPOT_TOOLS_WIN_TOOLCHAIN_BASE_URL environment variable."""
-  import urlparse
-  import urllib2
+  from urllib.parse import urljoin
+  from urllib.request import urlopen
+  from urllib.error import URLError
   from contextlib import closing
   temp_dir = tempfile.mkdtemp()
   assert os.path.basename(filename) == filename
   target_path = os.path.join(temp_dir, filename)
   base_url = ToolchainBaseURL()
-  src_url = urlparse.urljoin(base_url, filename)
+  src_url = urljoin(base_url, filename)
   try:
-    with closing(urllib2.urlopen(src_url)) as fsrc, \
+    with closing(urlopen(src_url)) as fsrc, \
          open(target_path, 'wb') as fdst:
       shutil.copyfileobj(fsrc, fdst)
-  except urllib2.URLError as e:
+  except URLError as e:
     RmDir(temp_dir)
     sys.exit('Failed to retrieve file: %s' % e)
   return temp_dir, target_path
```

Even after running it with these changes though, I got the following error:
```
Windows toolchain out of date or doesn't exist, updating (Pro)...
  current_hashes: e146e01913
  desired_hash: 3bda71a11e
Failed to retrieve file: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "src/build/vs_toolchain.py", line 573, in <module>
    sys.exit(main())
  File "src/build/vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "src/build/vs_toolchain.py", line 517, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Users\Sam\.electron_build_tools\third_party\depot_tools\bootstrap-2@3_8_10_chromium_19_bin\python3\bin\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
```

**Comment by jkleinsc** [comment]
Build tools should now pull in the right toolchain.  Please run `e check-for-updates` to get the latest build tools

**Comment by samuelmaddock** [comment]
I was still running into this issue when attempting to build on the Electron `14-x-y` branch. I think it will also happen on `15-x-y` and `main`.

Chromium's `src/DEPS` file points `depot_tools` to [a806594b95a39141fdbf1f359087a44ffb2deaaf](https://source.chromium.org/chromium/chromium/tools/depot_tools/+/a806594b95a39141fdbf1f359087a44ffb2deaaf) which is the problematic commit for Python 3 compatibility. `depot_tools` needs to point to [0aabd63461433b590f709544b41792d4e2f23c11](https://source.chromium.org/chromium/chromium/tools/depot_tools/+/0aabd63461433b590f709544b41792d4e2f23c11) to receive the Python 2/3 compatibility fix.

Adding a Chromium patch to change the `depot_tools` commit hash would likely fix this. However, I was able to get by using a somewhat low-tech method:
1. Run `e sync`
2. Wait for all dependencies to be synced to the proper commit.
3. Add a commit to `src/third_party/depot_tools` with the fixes in https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/2988315

Step 3 must happen before the toolchain update command runs. This is what worked for me, but obviously isn't a great solution.
