### ISSUE TITLE
e sync fail

### ISSUE THREAD

**Issue by dogeFu** [electron/build-tools#297]
```
________ running 'vpython.bat -vpython-spec src/.vpython -vpython-tool install' in 'D:\Git\electron'
________ running 'vpython3 -vpython-spec src/.vpython3 -vpython-tool install' in 'D:\Git\electron'
________ running 'python3 src/build/landmines.py' in 'D:\Git\electron'
________ running 'python3 src/third_party/depot_tools/update_depot_tools_toggle.py --disable' in 'D:\Git\electron'
________ running 'python3 src/tools/remove_stale_pyc_files.py src/android_webview/tools src/build/android src/gpu/gles2_conform_support src/infra src/ppapi src/printing src/third_party/blink/renderer/build/scripts src/third_party/blink/tools src/third_party/catapult src/tools' in 'D:\Git\electron'
________ running 'python3 src/build/vs_toolchain.py update --force' in 'D:\Git\electron'
Windows toolchain out of date or doesn't exist, updating (Pro)...
  current_hashes:
  desired_hash: e146e01913
Traceback (most recent call last):
  File "D:\Git\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 608, in <module>
    sys.exit(main())
  File "D:\Git\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 547, in main
    DoTreeMirror(toolchain_target_dir, args.desired_hash)
  File "D:\Git\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 363, in DoTreeMirror
    temp_dir, local_zip = DownloadUsingHttp(tree_sha1 + '.zip')
  File "D:\Git\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 313, in DownloadUsingHttp
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
Traceback (most recent call last):
  File "src/build/vs_toolchain.py", line 573, in <module>
    sys.exit(main())
  File "src/build/vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "src/build/vs_toolchain.py", line 517, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Users\Kay\.electron_build_tools\third_party\depot_tools\bootstrap-2@3_8_10_chromium_19_bin\python3\bin\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Kay\\.electron_build_tools\\third_party\\depot_tools\\bootstrap-2@3_8_10_chromium_19_bin\\python3\\bin\\python3.exe', 'D:\\Git\\electron\\src\\third_party\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'D:\\Git\\electron\\src\\build\\win_toolchain.json', 'e146e01913', '--force']' returned non-zero exit status 1.
Error: Command 'python3 src/build/vs_toolchain.py update --force' returned non-zero exit status 1 in D:\Git\electron
Windows toolchain out of date or doesn't exist, updating (Pro)...
  current_hashes:
  desired_hash: e146e01913
Traceback (most recent call last):
  File "D:\Git\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 608, in <module>
    sys.exit(main())
  File "D:\Git\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 547, in main
    DoTreeMirror(toolchain_target_dir, args.desired_hash)
  File "D:\Git\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 363, in DoTreeMirror
    temp_dir, local_zip = DownloadUsingHttp(tree_sha1 + '.zip')
  File "D:\Git\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 313, in DownloadUsingHttp
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
Traceback (most recent call last):
  File "src/build/vs_toolchain.py", line 573, in <module>
    sys.exit(main())
  File "src/build/vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "src/build/vs_toolchain.py", line 517, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Users\Kay\.electron_build_tools\third_party\depot_tools\bootstrap-2@3_8_10_chromium_19_bin\python3\bin\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Kay\\.electron_build_tools\\third_party\\depot_tools\\bootstrap-2@3_8_10_chromium_19_bin\\python3\\bin\\python3.exe', 'D:\\Git\\electron\\src\\third_party\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'D:\\Git\\electron\\src\\build\\win_toolchain.json', 'e146e01913', '--force']' returned non-zero exit status 1.

ERROR Error: Command failed: python C:\Users\Kay\.electron_build_tools\third_party\depot_tools\gclient.py sync --with_branch_heads --with_tags -vv
    at checkExecSyncError (node:child_process:826:11)
    at Object.execFileSync (node:child_process:864:15)
    at Object.depotExecFileSync [as execFileSync] (C:\Users\Kay\.electron_build_tools\src\utils\depot-tools.js:119:16)
    at runGClientSync (C:\Users\Kay\.electron_build_tools\src\e-sync.js:54:9)
    at Object.<anonymous> (C:\Users\Kay\.electron_build_tools\src\e-sync.js:76:3)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
```

Windows toolchain out of date or doesn't exist, updating (Pro)...
the DEPOT_TOOLS_WIN_TOOLCHAIN is set to be 0
Visual Studio 2019 is installed.
![image](https://user-images.githubusercontent.com/23008916/126205243-735ac29e-57ba-4dda-aabd-72fdac3470eb.png)

Any idea what 's wrong?

**Comment by dogeFu** [comment]
I change the commit of electron then run e sync and it work...........sad story.
