### ISSUE TITLE
ImportError: No module named httplib2

### ISSUE THREAD

**Issue by dsanders11** [electron/build-tools#330]
```
dsanders@Davids-MacBook-Pro ~ % e init --root=~/electron --bootstrap testing        
Checking for build-tools updates
Running "git pull --rebase --autostash" in /Users/dsanders/.electron_build_tools
build-tools is up-to-date
Cloning "depot_tools" into /Users/dsanders/.electron_build_tools/third_party/depot_tools
Updating /Users/dsanders/.electron_build_tools/third_party/depot_tools
Running "/Users/dsanders/.electron_build_tools/third_party/depot_tools/update_depot_tools"
Running "python /Users/dsanders/.electron_build_tools/third_party/depot_tools/gclient.py config --name src/electron --unmanaged https://github.com/electron/electron" in /Users/dsanders/electron
Traceback (most recent call last):
  File "/Users/dsanders/.electron_build_tools/third_party/depot_tools/gclient.py", line 108, in <module>
    import gclient_scm
  File "/Users/dsanders/.electron_build_tools/third_party/depot_tools/gclient_scm.py", line 29, in <module>
    import gerrit_util
  File "/Users/dsanders/.electron_build_tools/third_party/depot_tools/gerrit_util.py", line 16, in <module>
    import httplib2
ImportError: No module named httplib2
ERROR Error: Command failed: python /Users/dsanders/.electron_build_tools/third_party/depot_tools/gclient.py config --name src/electron --unmanaged https://github.com/electron/electron
    at checkExecSyncError (node:child_process:828:11)
    at Object.execFileSync (node:child_process:866:15)
    at Object.depotExecFileSync [as execFileSync] (/Users/dsanders/.electron_build_tools/src/utils/depot-tools.js:121:16)
    at runGClientConfig (/Users/dsanders/.electron_build_tools/src/e-init.js:85:9)
    at ensureRoot (/Users/dsanders/.electron_build_tools/src/e-init.js:102:5)
    at Object.<anonymous> (/Users/dsanders/.electron_build_tools/src/e-init.js:192:3)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

Seeing this on macOS, and @RaisinTen sees it on Windows, so seems like an across the board error.

**Comment by RaisinTen** [comment]
FYI, httplib2 was included using vpython in https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/1871763. So if we are running the depot_tools  python scripts correctly, this error probably shouldn't happen.
