### ISSUE TITLE
Windows toolchain out of date

### ISSUE THREAD

**Issue by codebytere** [electron/build-tools#360]
<details> <summary>Stacktrace</summary>

```
________ running 'python3 src/build/vs_toolchain.py update --force' in 'C:\Users\codebytere\Developer\electron-gn'
Windows toolchain out of date or doesn't exist, updating (Pro)...
  current_hashes: e146e01913
  desired_hash: e41785f09f
Failed to retrieve file: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "src/build/vs_toolchain.py", line 585, in <module>
    sys.exit(main())
  File "src/build/vs_toolchain.py", line 581, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "src/build/vs_toolchain.py", line 529, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Users\codebytere\.electron_build_tools\third_party\depot_tools\bootstrap-2@3_8_10_chromium_23_bin\python3\bin\lib\subprocess.py", line 364, in 
check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\codebytere\\.electron_build_tools\\third_party\\depot_tools\\bootstrap-2@3_8_10_chromium_23_bin\\python3\\bin\\python3.exe', 'C:\\Users\\codebytere\\Developer\\electron-gn\\src\\third_party\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'C:\\Users\\codebytere\\Developer\\electron-gn\\src\\build\\win_toolchain.json', 'e41785f09f', '--force']' returned non-zero exit status 1.  
Error: Command 'python3 src/build/vs_toolchain.py update --force' returned non-zero exit status 1 in C:\Users\codebytere\Developer\electron-gn
Windows toolchain out of date or doesn't exist, updating (Pro)...
  current_hashes: e146e01913
  desired_hash: e41785f09f
Failed to retrieve file: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "src/build/vs_toolchain.py", line 585, in <module>
    sys.exit(main())
  File "src/build/vs_toolchain.py", line 581, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "src/build/vs_toolchain.py", line 529, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Users\codebytere\.electron_build_tools\third_party\depot_tools\bootstrap-2@3_8_10_chromium_23_bin\python3\bin\lib\subprocess.py", line 364, in 
check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\codebytere\\.electron_build_tools\\third_party\\depot_tools\\bootstrap-2@3_8_10_chromium_23_bin\\python3\\bin\\python3.exe', 'C:\\Users\\codebytere\\Developer\\electron-gn\\src\\third_party\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'C:\\Users\\codebytere\\Developer\\electron-gn\\src\\build\\win_toolchain.json', 'e41785f09f', '--force']' returned non-zero exit status 1.  
```

</details>

cc @jkleinsc

**Comment by MarshallOfSound** [comment]
@codebytere We just alias hashes to each other, we don't have a super good process for exactly matching Chromium's hashes anyway so as long as the hash alias works (like the build succeeds) we just do that.

https://github.com/electron/build-tools/blob/80d627c18ce348b8bae0826ec8562992d86b6d0c/src/utils/depot-tools.js#L57-L59

**Comment by codebytere** [comment]
Missed https://github.com/electron/build-tools/commit/80d627c18ce348b8bae0826ec8562992d86b6d0c since there appears to not have been a PR?

We should add https://chromium-review.googlesource.com/c/chromium/src/+/3550827 too.

**Comment by MarshallOfSound** [comment]
@codebytere Until recently we didn't use the windows toolchain, I think that was a 2021 development
