### ISSUE TITLE
REGRESSION: downloading goma client is broken

### ISSUE THREAD

**Issue by aslushnikov** [electron/build-tools#367]
The following no longer works:

```bash
git clone --single-branch --branch main https://github.com/electron/build-tools/ electron-build-tools
cd electron-build-tools
npm install
mkdir -p third_party
./src/e update-goma msftGoma
```

Error:
```
Downloading "https://electron-build-tools.s3-us-west-2.amazonaws.com/build-dependencies/45e4d2d4fcb902aba37e52e1a218523288de3df1e9a89a80086e3994347f851f/goma-mac-arm64.tgz" into /Users/andreylushnikov/prog/playwright/browser_patches/chromium/electron-build-tools/third_party/goma-mac-arm64.tgz
/Users/andreylushnikov/prog/playwright/browser_patches/chromium/electron-build-tools/node_modules/progress/lib/node-progress.js:164
  incomplete = Array(Math.max(0, width - completeLength + 1)).join(this.chars.incomplete);
               ^

RangeError: Invalid array length
    at ProgressBar.render (/Users/andreylushnikov/prog/playwright/browser_patches/chromium/electron-build-tools/node_modules/progress/lib/node-progress.js:164:16)
    at ProgressBar.tick (/Users/andreylushnikov/prog/playwright/browser_patches/chromium/electron-build-tools/node_modules/progress/lib/node-progress.js:97:8)
    at PassThrough.<anonymous> (/Users/andreylushnikov/prog/playwright/browser_patches/chromium/electron-build-tools/src/download.js:20:13)
    at PassThrough.emit (node:events:402:35)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at PassThrough.Readable.push (node:internal/streams/readable:228:10)
    at node:internal/streams/transform:192:12
    at PassThrough._transform (node:internal/streams/passthrough:46:3)
    at PassThrough.Transform._write (node:internal/streams/transform:184:23)
ERROR Got hash for downloaded file "90a7472b3fc130a656d6bd1cdbcbca5d124efb83354fce961534f6b23d7f30f8" which did not match "45e4d2d4fcb902aba37e52e1a218523288de3df1e9a89a80086e3994347f851f". Halting now
```

Looks like this is due to https://github.com/electron/build-tools/commit/7faf1debd72c7aa682e54cdedfc0d734dc0fbe85

**Comment by MarshallOfSound** [comment]
Fixed in [71d258e](https://github.com/electron/build-tools/commit/71d258e6e9654d8172fdf3404eba0e062da32cb7)
