### ISSUE TITLE
goma login does not work with python3

### ISSUE THREAD

**Issue by aslushnikov** [electron/build-tools#374]
MacOS 12.2 removed Python 2 from the system, so we now have python 3 by default.
However, using `python3 ./goma_auth.py login` command crashes for me with the following stack:

```sh
...
3. How long data will be kept?

Contents in source code and header files will be kept at most 153 days
since last used.

Do you agree to our data usage policy? (y/n) -->y
You have agreed.
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 60613)
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socketserver.py", line 683, in process_request
_thread
    self.finish_request(request, client_address)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/server.py", line 415, in handle_one_reque
st
    method()
  File "/Users/andreylushnikov/prog/playwright/browser_patches/chromium/electron-build-tools/third_party/goma/goma_auth.py", line 313, in do_GET
    self.wfile.write('<html><head><title>Authentication Status</title></head>')
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socketserver.py", line 826, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'
```

### workaround

Install python 2 on MacOS: https://www.python.org/ftp/python/2.7.18/python-2.7.18-macosx10.9.pkg

**Comment by MarshallOfSound** [comment]
@jkleinsc I think this is msft goma client specific?

**Comment by jkleinsc** [comment]
@MarshallOfSound that is correct.  @aslushnikov I'll have a fix up shortly.
