### ISSUE TITLE
build failed: missing file

### ISSUE THREAD

**Issue by Tarrowren** [electron/build-tools#400]
env:
windows 10
node 14.19.3

missing file v8_union_gpucanvascontext_imagebitmaprenderingcontext_offscreencanvasrenderingcontext2d_webgl2renderingcontext_webglrenderingcontext.h and v8_union_gpucanvascontext_imagebitmaprenderingcontext_offscreencanvasrenderingcontext2d_webgl2renderingcontext_webglrenderingcontext.cc.

```
%User%>e build
Running "ninja.exe -j 200 electron" in %User%\Desktop\jscode\github\electron-test\electron\src\out\Testing
[347/38278] ACTION //third_party/blink/renderer/bindings:generate_bindings_all(//build/toolchain/win:win_clang_x64)
FAILED: gen/third_party/blink/renderer/bindings/core/v8/v8_align_setting.cc gen/third_party/blink/renderer/bindings/core/v8/v8_align_setting.h ...
%User%/.electron_build_tools/third_party/depot_tools/bootstrap-2@3_8_10_chromium_23_bin/python3/bin/python3.exe ../../third_party/blink/renderer/bindings/scripts/generate_bindings.py --web_idl_database gen/third_party/blink/renderer/bindings/web_idl_database.pickle --root_src_dir ../../ --root_gen_dir gen --output_reldir core=third_party/blink/renderer/bindings/core/v8/ --output_reldir modules=third_party/blink/renderer/bindings/modules/v8/ enumeration callback_function callback_interface dictionary interface namespace observable_array typedef union
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "%User%\.electron_build_tools\third_party\depot_tools\bootstrap-2@3_8_10_chromium_23_bin\python3\bin\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "%User%\Desktop\jscode\github\electron-test\electron\src\third_party\blink\renderer\bindings\scripts\bind_gen\union.py", line 1101, in generate_union
    write_code_node_to_file(header_node, path_manager.gen_path_to(header_path))
  File "%User%\Desktop\jscode\github\electron-test\electron\src\third_party\blink\renderer\bindings\scripts\bind_gen\codegen_utils.py", line 207, in write_code_node_to_file
    web_idl.file_io.write_to_file_if_changed(
  File "%User%\Desktop\jscode\github\electron-test\electron\src\third_party\blink\renderer\bindings\scripts\web_idl\file_io.py", line 45, in write_to_file_if_changed
    with open(filepath, 'wb') as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '%User%\\Desktop\\jscode\\github\\electron-test\\electron\\src\\out\\Testing\\gen\\third_party\\blink\\renderer\\bindings\\modules\\v8\\v8_union_gpucanvascontext_imagebitmaprenderingcontext_offscreencanvasrenderingcontext2d_webgl2renderingcontext_webglrenderingcontext.h'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../../third_party/blink/renderer/bindings/scripts/generate_bindings.py", line 126, in <module>
    main()
  File "../../third_party/blink/renderer/bindings/scripts/generate_bindings.py", line 121, in main
    task_queue.run(report_progress)
  File "%User%\Desktop\jscode\github\electron-test\electron\src\third_party\blink\renderer\bindings\scripts\bind_gen\task_queue.py", line 81, in run
    self._run_in_parallel(report_progress)
  File "%User%\Desktop\jscode\github\electron-test\electron\src\third_party\blink\renderer\bindings\scripts\bind_gen\task_queue.py", line 119, in _run_in_parallel
    worker_task.get()  # Let |get()| raise an exception.
  File "%User%\.electron_build_tools\third_party\depot_tools\bootstrap-2@3_8_10_chromium_23_bin\python3\bin\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '%User%\\Desktop\\jscode\\github\\electron-test\\electron\\src\\out\\Testing\\gen\\third_party\\blink\\renderer\\bindings\\modules\\v8\\v8_union_gpucanvascontext_imagebitmaprenderingcontext_offscreencanvasrenderingcontext2d_webgl2renderingcontext_webglrenderingcontext.h'
[453/38278] CXX obj/third_party/perfetto/src/trace_processor/storage/storage/trace_storage.obj
ninja: build stopped: subcommand failed.
ERROR Error: Command failed: ninja.exe -j 200 electron
    at checkExecSyncError (child_process.js:790:11)
    at Object.execFileSync (child_process.js:827:15)
    at Object.depotExecFileSync [as execFileSync] (%User%\.electron_build_tools\src\utils\depot-tools.js:121:16)
    at runNinja (%User%\.electron_build_tools\src\e-build.js:84:9)
    at Object.<anonymous> (%User%\.electron_build_tools\src\e-build.js:137:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
```

**Comment by Tarrowren** [comment]
Of course, I tried step by step according to the example and always failed at the final build

**Comment by Tarrowren** [comment]
Of course, I tried step by step according to the example and always failed at the final build

**Comment by codebytere** [comment]
This is unfortunately not a build-tools issue - if it still occurs using a fresh build with Node.js v16 please consider opening an issue on `electron/electron`
