### ISSUE TITLE
build fails:  'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by nincool** [electron/build-tools#425]
when run "e build",  we get :

```
 D:\workspace\test\electron>e build
Running "python3.bat goma_ctl.py ensure_start" in C:\Users\Administrator\.electron_build_tools\third_party\goma
Not logged in
using C:\Users\ADMINI~1\AppData\Local\Temp\goma as tmpdir

Traceback (most recent call last):
  File "goma_ctl.py", line 2558, in <module>
    sys.exit(main())
  File "goma_ctl.py", line 2553, in main
    goma.Dispatch(sys.argv[1:])
  File "goma_ctl.py", line 1163, in Dispatch
    self._action_mappings.get(args[0], self._DefaultAction)()
  File "goma_ctl.py", line 670, in _EnsureStartCompilerProxy
    self._GenericStartCompilerProxy(ensure=True)
  File "goma_ctl.py", line 609, in _GenericStartCompilerProxy
    self._compiler_proxy_running = self._env.CompilerProxyRunning()
  File "goma_ctl.py", line 2137, in CompilerProxyRunning
    return self._ProcessRunning(self._COMPILER_PROXY)
  File "goma_ctl.py", line 2108, in _ProcessRunning
    return bool(self._GetProcessImagePid(image_name))
  File "goma_ctl.py", line 2096, in _GetProcessImagePid
    output = process.communicate()[0]
  File "goma_ctl.py", line 436, in communicate
    stdout, stderr = super(PopenWithCheck, self).communicate(input)
  File "goma_ctl.py", line 426, in communicate
    return _DecodeBytesOnPython3(stdout), _DecodeBytesOnPython3(stderr)
  File "goma_ctl.py", line 133, in _DecodeBytesOnPython3
    return data.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte
ERROR Error: Command failed: python3.bat goma_ctl.py ensure_start
    at checkExecSyncError (node:child_process:871:11)
    at Object.execFileSync (node:child_process:907:15)
    at Object.depotExecFileSync [as execFileSync] (C:\Users\Administrator\.electron_build_tools\src\utils\depot-tools.js:127:23)
    at Object.ensureGomaStart [as ensure] (C:\Users\Administrator\.electron_build_tools\src\utils\goma.js:197:9)
    at runNinja (C:\Users\Administrator\.electron_build_tools\src\e-build.js:43:10)
    at Command.<anonymous> (C:\Users\Administrator\.electron_build_tools\src\e-build.js:121:7)
    at Command.listener [as _actionHandler] (C:\Users\Administrator\.electron_build_tools\node_modules\commander\lib\command.js:480:17)
    at C:\Users\Administrator\.electron_build_tools\node_modules\commander\lib\command.js:1234:65
    at Command._chainOrCall (C:\Users\Administrator\.electron_build_tools\node_modules\commander\lib\command.js:1151:12)
```
I also use python2.7 or python3.11 direct run "goma_ctl.py ensure_start", but get same error.

**Comment by codebytere** [comment]
@nincool Is this still happening?

**Comment by 759852125** [comment]
C:\Users\Administrator\.electron_build_tools\third_party\goma\goma_ctl.py

133 line replace with

`return data.decode('gb18030')`

**Comment by mccare** [comment]
Ran into the same problem, the fix was working (Windows 10, German language). .sha file shows `f4f38d03e94b695bf2511b34759e2752a695e92772a1f53d81c2840db731b541`

**Comment by codebytere** [comment]
Unfortunately this is an upstream issue - we use this library from Microsoft. I can see what if anything there is to do but the issue won't be solved on this repo.
