### ISSUE TITLE
Error when build specific version through git checkout tags/vXX.Y.Z -b vXX.Y.Z

### ISSUE THREAD

**Issue by alexivaner** [electron/build-tools#427]
**Hello everyone,**

**I run this command** 

```
npm i -g @electron/build-tools
e init --root=~/electron --bootstrap testing
e show src
#cd to `e show src` result

#Sync dependencies with the current branch
e sync

# Build Electron
e build
```

and successfully build electrons until the end.

**But I want to specifically build v20.0.0, so I am running this one**

```
# Checkout the desired Electron version (in this case, 20.0.0)
git checkout tags/v20.0.0 -b v20.0.0

# Sync dependencies with the current branch
e sync

# Build Electron
e build

```
**Then the built resulting error like this:**
```
Running "ninja.exe -j 200 electron" in D:\Kerja\Octon\electron_\src\out\Testing
[0/1] Regenerating ninja files
[0/1] Regenerating ninja files
ninja: error: FindFirstFileExA(../../buildtools/third_party/libc++/trunk/include/__string): The directory name is invalid.

ERROR Error: Command failed: ninja.exe -j 200 electron
    at checkExecSyncError (node:child_process:826:11)
    at Object.execFileSync (node:child_process:864:15)
    at Object.depotExecFileSync [as execFileSync] (C:\Users\hutom\.electron_build_tools\src\utils\depot-tools.js:127:23)
    at runNinja (C:\Users\hutom\.electron_build_tools\src\e-build.js:60:9)
    at Command.<anonymous> (C:\Users\hutom\.electron_build_tools\src\e-build.js:121:7)
    at Command.listener [as _actionHandler] (C:\Users\hutom\.electron_build_tools\node_modules\commander\lib\command.js:480:17)
    at C:\Users\hutom\.electron_build_tools\node_modules\commander\lib\command.js:1234:65
    at Command._chainOrCall (C:\Users\hutom\.electron_build_tools\node_modules\commander\lib\command.js:1151:12)
    at Command._parseCommand (C:\Users\hutom\.electron_build_tools\node_modules\commander\lib\command.js:1234:27)
    at Command.parse (C:\Users\hutom\.electron_build_tools\node_modules\commander\lib\command.js:889:10)


```
**_When I check out back to the previous branch and sync again, the build could be executed successfully.
How I could build the specific version v20.0.0? Thank you._**

**Comment by MarshallOfSound** [comment]
Are you checking out v20.0.0 in "src" or "src/electron"

**Comment by alexivaner** [comment]
In "src/electron"

**Comment by alexivaner** [comment]
Hi, anyone facing this issue too?
