### ISSUE TITLE
Failed to install build-tools:  Error: Command "yarn install" failed with exit code null

### ISSUE THREAD

**Issue by hailangljb** [electron/build-tools#475]
### Operating System
]([url]([url](url)))

root@yisu-641d35059ae14:~# npm i -g @electron/build-tools

> @electron/build-tools@1.1.0 preinstall /home/jb/soft/node/lib/node_modules/@electron/build-tools
> node preinstall.js

Failed to install build-tools:  Error: Command "yarn install" failed with exit code null
    at throwForBadSpawn (/home/jb/soft/node/lib/node_modules/@electron/build-tools/preinstall.js:10:11)
    at install (/home/jb/soft/node/lib/node_modules/@electron/build-tools/preinstall.js:44:5)
    at Object.<anonymous> (/home/jb/soft/node/lib/node_modules/@electron/build-tools/preinstall.js:64:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @electron/build-tools@1.1.0 preinstall: `node preinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @electron/build-tools@1.1.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-03-31T13_42_36_155Z-debug.log

**Comment by codebytere** [comment]
You likely need to ensure you have correct write permissions.
