### ISSUE TITLE
`e init` error on macOS M1: `Not logged in. Run this command and retry the build:     pushd $GOMACLIENTDIR && python3 goma_auth.py login && popd`

### ISSUE THREAD

**Issue by MattTreichelYeah** [electron/build-tools#501]
### Operating System
macOS Ventura 13.4.1 (c)
arm64/M1 chip

### Expected Behavior
Running `e init --root=~/electron --bootstrap testing` per the README.

### Actual Behavior

```
...
[31619/47887] CXX obj/components/guest_view/browser/browser/guest_view_event.o
FAILED: obj/components/guest_view/browser/browser/guest_view_event.o
/Users/matt-treichel/.electron_build_tools/third_party/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/components/guest_view/browser/browser/guest_view_event.o.d -DDCHECK_ALWAYS_ON=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_ENABLE_ASSERTIONS=1 -DCR_XCODE_VERSION=1430 -DCR_CLANG_REVISION=\"llvmorg-17-init-16420-g0c545a44-2\" -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -DCR_LIBCXX_REVISION=84fb809dd6dae36d556dc0bb702c6cc2ce9d4b80 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DENABLE_IPC_FUZZER -DWEBP_EXTERN=extern -DUSE_EGL -DCRASHPAD_ZLIB_SOURCE_EXTERNAL -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DGOOGLE_PROTOBUF_INTERNAL_DONATE_STEAL_INLINE=0 -DHAVE_PTHREAD -DWEBRTC_ENABLE_AVX2 -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_MAC -DABSL_ALLOCATOR_NOTHROW=1 -DLOGGING_INSIDE_WEBRTC -DSK_ENABLE_SKSL -DSK_UNTIL_CRBUG_1187654_IS_FIXED -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_WIN_FONTMGR_NO_SIMULATIONS -DSK_DISABLE_LEGACY_SKSURFACE_METHODS -DSK_DISABLE_LEGACY_GRAPHITE_IMAGE_FACTORIES -DSK_DISABLE_LEGACY_GRAPHITE_IMAGE_METHODS -DSK_DISABLE_LEGACY_SKSURFACE_FACTORIES -DSK_DISABLE_LEGACY_SKSURFACE_FLUSH -DSK_DISABLE_LEGACY_SKSURFACE_AS_IMAGE -DSK_DISABLE_LEGACY_SKSURFACE_DISPLAYLIST -DSK_CODEC_DECODES_JPEG -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_JPEG -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_HAS_WUFFS_LIBRARY -DSK_DISABLE_LEGACY_CANVAS_FLUSH -DSK_LEGACY_GPU_GETTERS_CONST -DSK_BUILD_FOR_MAC -DSK_GANESH -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DSK_GL -DSK_GRAPHITE -DSK_DAWN -DSK_METAL -DLEVELDB_PLATFORM_CHROMIUM=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DV8_COMPRESS_POINTERS -DV8_COMPRESS_POINTERS_IN_SHARED_CAGE -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_ENABLE_SANDBOX -DV8_DEPRECATION_WARNINGS -DCPPGC_CAGED_HEAP -DCPPGC_YOUNG_GENERATION -DCPPGC_POINTER_COMPRESSION -DCPPGC_SLIM_WRITE_BARRIER -I../.. -Igen -I../../buildtools/third_party/libc++ -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -Igen/third_party/dawn/include -I../../third_party/dawn/include -I../../third_party/libwebp/src/src -I../../third_party/libyuv/include -I../../third_party/jsoncpp/source/include -I../../third_party/khronos -I../../gpu -Igen/third_party/private_membership/src -Igen/third_party/shell-encryption/src -Igen/components/policy/proto -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/crashpad/crashpad -I../../third_party/crashpad/crashpad/compat/mac -I../../third_party/crashpad/crashpad/compat/non_win -I../../third_party/zlib -I../../third_party/ipcz/include -I../../third_party/ced/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../net/third_party/quiche/overrides -I../../net/third_party/quiche/src/quiche/common/platform/default -I../../net/third_party/quiche/src -Igen/net/third_party/quiche/src -I../../third_party/webrtc_overrides -I../../third_party/webrtc -Igen/third_party/webrtc -I../../third_party/skia -Igen/third_party/skia -I../../third_party/wuffs/src/release/c -I../../third_party/libwebm/source -I../../third_party/mesa_headers -I../../third_party/leveldatabase -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase/src/include -I../../third_party/libaom/source/libaom -I../../v8/include -Igen/v8/include -Wall -Werror -Wextra -Wimplicit-fallthrough -Wextra-semi -Wunreachable-code-aggressive -Wthread-safety -Wunguarded-availability -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unneeded-internal-declaration -Wenum-compare-conditional -Wno-ignored-pragma-optimize -Wno-deprecated-builtins -Wno-bitfield-constant-conversion -Wno-deprecated-this-capture -Wshadow -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing -fstack-protector -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -ffp-contract=off -fcomplete-member-pointers -arch arm64 -fno-global-isel -mno-outline -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -ffile-compilation-dir=. -no-canonical-prefixes -ftrivial-auto-var-init=pattern -O2 -fno-omit-frame-pointer -gdwarf-4 -g1 -gdwarf-aranges -isysroot sdk/xcode_links/MacOSX13.3.sdk -mmacos-version-min=10.15 -fvisibility=hidden -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ref-template-as-trivial-member -Xclang -plugin-arg-find-bad-constructs -Xclang check-stack-allocated -Xclang -plugin-arg-find-bad-constructs -Xclang check-raw-ptr-fields -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ptr-exclude-path=testing/platform_test.h -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ptr-exclude-path=sandbox/mac/ -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ptr-exclude-path=chrome/browser/ui/cocoa/touchbar/browser_window_default_touch_bar.mm -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ptr-exclude-path=device/bluetooth/test/mock_bluetooth_central_manager_mac.mm -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ptr-exclude-path=device/bluetooth/test/mock_bluetooth_cbperipheral_mac.mm -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ptr-exclude-path=ui/views/controls/native/native_view_host_mac_unittest.mm -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ptr-exclude-path=ui/views/widget/native_widget_mac_unittest.mm -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ptr-exclude-path=ui/views/controls/native/native_view_host_mac_unittest.mm -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ptr-exclude-path=um/winnt.h -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ptr-exclude-path=chromeos/assistant/internal/ -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -DPROTOBUF_ALLOW_DEPRECATED=1 -std=c++20 -Wno-trigraphs -fno-exceptions -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include -fvisibility-inlines-hidden -c ../../components/guest_view/browser/guest_view_event.cc -o obj/components/guest_view/browser/browser/guest_view_event.o
GOMA:clang++ compiling ../../components/guest_view/browser/guest_view_event.cc:*ERROR*: compiler_proxy [2m5.801493041s]:
**************************************************************
Not logged in. Run this command and retry the build:
    pushd $GOMACLIENTDIR && python3 goma_auth.py login && popd
**************************************************************

[31662/47887] CXX obj/components/pdf/renderer/renderer/pdf_view_web_plugin_client.o
ninja: build stopped: subcommand failed.
ERROR Error: Command failed: ninja -j 200 electron
    at checkExecSyncError (node:child_process:885:11)
    at Object.execFileSync (node:child_process:921:15)
    at Object.depotExecFileSync [as execFileSync] (/Users/matt-treichel/.electron_build_tools/src/utils/depot-tools.js:131:23)
    at runNinja (/Users/matt-treichel/.electron_build_tools/src/e-build.js:60:9)
    at Command.<anonymous> (/Users/matt-treichel/.electron_build_tools/src/e-build.js:121:7)
    at Command.listener [as _actionHandler] (/Users/matt-treichel/.electron_build_tools/node_modules/commander/lib/command.js:480:17)
    at /Users/matt-treichel/.electron_build_tools/node_modules/commander/lib/command.js:1234:65
    at Command._chainOrCall (/Users/matt-treichel/.electron_build_tools/node_modules/commander/lib/command.js:1151:12)
    at Command._parseCommand (/Users/matt-treichel/.electron_build_tools/node_modules/commander/lib/command.js:1234:27)
ERROR Error: Command failed: /usr/local/bin/node /Users/matt-treichel/.electron_build_tools/src/e build
    at checkExecSyncError (node:child_process:885:11)
    at Object.execFileSync (node:child_process:921:15)
    at Command.<anonymous> (/Users/matt-treichel/.electron_build_tools/src/e-init.js:199:22)
    at Command.listener [as _actionHandler] (/Users/matt-treichel/.electron_build_tools/node_modules/commander/lib/command.js:480:17)
    at /Users/matt-treichel/.electron_build_tools/node_modules/commander/lib/command.js:1234:65
    at Command._chainOrCall (/Users/matt-treichel/.electron_build_tools/node_modules/commander/lib/command.js:1151:12)
    at Command._parseCommand (/Users/matt-treichel/.electron_build_tools/node_modules/commander/lib/command.js:1234:27)
    at Command.parse (/Users/matt-treichel/.electron_build_tools/node_modules/commander/lib/command.js:889:10)
    at Object.<anonymous> (/Users/matt-treichel/.electron_build_tools/src/e-init.js:205:4)
```

If I try to run the recommended command, it can't find that file:

```
matt-treichel@MacBook-Pro ~ % pushd $GOMACLIENTDIR && python3 goma_auth.py login && popd
~ ~
/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/matt-treichel/goma_auth.py': [Errno 2] No such file or directory
```

Searching through `.electron_build_tools` and I found that file, but it took me to a page where after authorizing my Github account https://auth.notgoma.com/github_callback, I see this:

![image](https://github.com/electron/build-tools/assets/6729569/cc9666ec-c068-4731-87d9-d141b0f58ec0)

### To Reproduce

Running `e init --root=~/electron --bootstrap testing` per the README.

I've been having issues with Xcode and python errors before this, but I thought I've fixed them. It's been a bit of a hell after upgrading to the M1 Mac.

```
matt-treichel@MacBook-Pro ~ % /usr/bin/xcodebuild -version
Xcode 14.3.1
Build version 14E300c
```
```
matt-treichel@MacBook-Pro ~ % python --version
Python 3.9.6
matt-treichel@MacBook-Pro ~ % python3 --version
Python 3.11.3
```

**Comment by MattTreichelYeah** [comment]
Well, I ran the same `e init` command one more time and this time it passed. I'm not sure if at least accepting the privacy policy from `goma_auth.py` helped, or if this is some kind of intermittent issue.

**Comment by codebytere** [comment]
@MattTreichelYeah you shouldn't be using the GOMA client at all - the default is cache usage. If you open your testing config, what does it look like? it should be at `~/electron_build_tools/configs/evm.testing.yml` or similar (or json if you went that route)

**Comment by MattTreichelYeah** [comment]
@codebytere Looks like this

```
{
  "$schema": "file:///Users/matt-treichel/.electron_build_tools/evm-config.schema.json",
  "goma": "cache-only",
  "root": "/Users/matt-treichel/electron",
  "remotes": {
    "electron": {
      "origin": "git@github.com:electron/electron.git"
    }
  },
  "gen": {
    "args": [
      "import(\"//electron/build/args/testing.gn\")",
      "import(\"/Users/matt-treichel/.electron_build_tools/third_party/goma.gn\")"
    ],
    "out": "Testing"
  },
  "env": {
    "CHROMIUM_BUILDTOOLS_PATH": "/Users/matt-treichel/electron/src/buildtools",
    "GIT_CACHE_PATH": "/Users/matt-treichel/.git_cache",
    "GOMA_CACHE_DIR": "/Users/matt-treichel/.goma_cache",
    "GOMA_DEPS_CACHE_FILE": "deps-cache",
    "GOMA_COMPILER_INFO_CACHE_FILE": "compiler-info-cache",
    "GOMA_LOCAL_OUTPUT_CACHE_DIR": "/Users/matt-treichel/.goma_output_cache"
  }
}
```

Looks like it has the value you'd expect. I had never touched this and didn't think I did anything abnormal except mess with the version of Xcode loaded to get past errors. It ran perfectly fine one run after the errors in the report without any change so maybe this is something intermittent?

**Comment by dabretin** [comment]
Same problem here (linux mint) and the only way I find is to add `--goma=none` (`cache-only` does nothing) to `e init --root=~/electron --goma=none --bootstrap testing`

**Comment by codebytere** [comment]
@MattTreichelYeah @dabretin found a moment to look into this and put up a PR which should fix it!

**Comment by WEI3M** [comment]
The PR seems to have fixed part of the problem, not all. When I run `e build` command and rely on it to launch the goma service,  it will fail at some point. The log looks like this:
```
...
Running "python3 goma_ctl.py ensure_start" in /Users/wei/.electron_build_tools/third_party/goma
...
...
GOMA:clang++ compiling ../../third_party/blink/renderer/core/html/forms/date_time_field_elements.cc:*ERROR*: compiler_proxy [2.091656625s]:
**************************************************************
Not logged in. Run this command and retry the build:
    pushd $GOMACLIENTDIR && python3 goma_auth.py login && popd
**************************************************************
```
I wonder if the child_process of goma somehow got terminated so that it failed but not at the very beginning. My current workaround is:
1. Manually start/restart GOMA: 
```
export GOMACTL_SKIP_AUTH='true'
goma_ctl restart 
```
2. Since I'm running it on m1 mac with only 8G mem, I change the default `-j` to `10` by modifying the `~/.electron_build_tools/src/e-build.js`
https://github.com/electron/build-tools/blob/ac4f9a9063f29baa5b356a71b8182b36889a5405/src/e-build.js#L45

3. `e build`

It's been working so far so good, despite that with only 8cores / 8G mem, it's not that fast either. The goma cache helps a lot though.
