### ISSUE TITLE
 e test error

### ISSUE THREAD

**Issue by LikeNeko** [electron/build-tools#511]
### Operating System
macOS 11.4 on M1 chip

### Expected Behavior
I expected the Electron application to initialize successfully when running the command `e init --root=~/NodeProject/electron/testing --goma=none --bootstrap testing`

### Actual Behavior
When running the `e test` command, the initialization fails with the following error message:

```
ninja: error: unknown target 'third_party/electron_node:headers'
ERROR Error: Command failed: ninja third_party/electron_node:headers
```

A full log of the error message is provided in the Additional Information section.

### To Reproduce
1. Open Terminal
2. Navigate to the project directory (`cd ~/NodeProject/electron/testing`)
3. Run the command `e init --root=~/NodeProject/electron/testing --goma=none --bootstrap testing`

### Screenshots
N/A

### Additional Information
Here is the full log of the error message:

```
Running "e load-xcode --quiet"
INFO Building third_party/electron_node:headers with Goma disabled
Running "ninja third_party/electron_node:headers" in /Users/Neko/NodeProject/electron/testing/src/out/Testing
ninja: error: unknown target 'third_party/electron_node:headers'
ERROR Error: Command failed: ninja third_party/electron_node:headers
    at checkExecSyncError (node:child_process:885:11)
    at Object.execFileSync (node:child_process:921:15)
    at Object.depotExecFileSync [as execFileSync] (/Users/Neko/.electron_build_tools/src/utils/depot-tools.js:131:23)
    at runNinja (/Users/Neko/.electron_build_tools/src/e-build.js:60:9)
    at Command.<anonymous> (/Users/Neko/.electron_build_tools/src/e-build.js:121:7)
    at Command.listener [as _actionHandler] (/Users/Neko/.electron_build_tools/node_modules/commander/lib/command.js:480:17)
    at /Users/Neko/.electron_build_tools/node_modules/commander/lib/command.js:1234:65
    at Command._chainOrCall (/Users/Neko/.electron_build_tools/node_modules/commander/lib/command.js:1151:12)
    at Command._parseCommand (/Users/Neko/.electron_build_tools/node_modules/commander/lib/command.js:1234:27)
ERROR Error: Command failed: /usr/local/bin/node /Users/Neko/.electron_build_tools/src/e build node:headers
    at checkExecSyncError (node:child_process:885:11)
    at Object.execFileSync (node:child_process:921:15)
    at ensureNodeHeaders (/Users/Neko/.electron_build_tools/src/utils/headers.js:30:18)
    at Command.<anonymous> (/Users/Neko/.electron_build_tools/src/e-test.js:71:9)
    at Command.listener [as _actionHandler] (/Users/Neko/.electron_build_tools/node_modules/commander/lib/command.js:480:17)
    at /Users/Neko/.electron_build_tools/node_modules/commander/lib/command.js:1234:65
    at Command._chainOrCall (/Users/Neko/.electron_build_tools/node_modules/commander/lib/command.js:1151:12)
    at Command._parseCommand (/Users/Neko/.electron_build_tools/node_modules/commander/lib/command.js:1234:27)
    at Command.parse (/Users/Neko/.electron_build_tools/node_modules/commander/lib/command.js:889:10)
```

**Comment by LikeNeko** [comment]
I've already searched through the issues in the electron/electron repository and this repository, but I haven't found a solution to this problem.

**Comment by jkleinsc** [comment]
Looks like this is a side effect of https://github.com/electron/electron/pull/39589.
