### ISSUE TITLE
Can no longer compile on Windows, "gn gen" can't parse arguments properly

### ISSUE THREAD

**Issue by andrewsml** [electron/build-tools#582]
`e build` command fails because `gn gen` can't parse command line arguments properly.
it seems that something with quotation marks or escaping.  

```
e build electron:dist
Running "C:\Users\ElectronBuildMachine\.electron_build_tools\third_party\depot_tools\gn.bat gen out/Release --args=import("//electron/build/args/release.gn") use_remoteexec = true" in c:\workspace\electron_canvid\electron\src
ERROR Need exactly one build directory to generate.
I expected something more like "gn gen out/foo"
You can also see "gn help gen".
ERROR Error: Command failed: C:\Users\ElectronBuildMachine\.electron_build_tools\third_party\depot_tools\gn.bat gen out/Release --args=import("//electron/build/args/release.gn") use_remoteexec = true
    at checkExecSyncError (node:child_process:890:11)
    at Object.execFileSync (node:child_process:926:15)
    at Object.depotExecFileSync [as execFileSync] (C:\Users\ElectronBuildMachine\.electron_build_tools\src\utils\depot-tools.js:146:23)
    at runGNGen (C:\Users\ElectronBuildMachine\.electron_build_tools\src\e-build.js:22:9)
    at ensureGNGen (C:\Users\ElectronBuildMachine\.electron_build_tools\src\e-build.js:27:41)
    at runNinja (C:\Users\ElectronBuildMachine\.electron_build_tools\src\e-build.js:62:3)
    at Command.<anonymous> (C:\Users\ElectronBuildMachine\.electron_build_tools\src\e-build.js:127:9)
    at Command.listener [as _actionHandler] (C:\Users\ElectronBuildMachine\.electron_build_tools\node_modules\commander\lib\command.js:480:17)
    at C:\Users\ElectronBuildMachine\.electron_build_tools\node_modules\commander\lib\command.js:1234:65
```
### Operating System

Windows 10 (22H2)
### Expected Behavior

`e build`  command succeeds

**Comment by lymhappy123** [comment]
I also encountered the same problem, how to solve it?

**Comment by reitowo** [comment]
+1
