### ISSUE TITLE
build v22 faild, got `Windows toolchain out of date or doesn't exist, updating (Pro) error on e sync`

### ISSUE THREAD

**Issue by githoniel** [electron/build-tools#595]
### Operating System
Microsoft Windows [Version 10.0.19045.4412]

### Expected Behavior

```bash
npm i -g @electron/build-tools
e init main-release -i release
e sync
e build // every is ok right now

cd electron/src/electron
git checkout tags/v22.3.27 -b 22.3.27
e sync // get wrong here
```

### Actual Behavior

```
G:\\git\\electron\\src\\third_party\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'G:\\git\\electron\\src\\build\\win_toolchain.json', '3a908a0f94', '--force']' returned non-zero exit status 1.
Error: Command 'python3 src/build/vs_toolchain.py update --force' returned non-zero exit status 1 in G:\git\electron
G:\git\electron\src\build\vs_toolchain.py:12: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
Windows toolchain out of date or doesn't exist, updating (Pro)...
  current_hashes: 3ba76c5c20
  desired_hash: 3a908a0f94
Failed to retrieve file: <urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)>
Traceback (most recent call last):
  File "G:\git\electron\src\build\vs_toolchain.py", line 585, in <module>
    sys.exit(main())
             ^^^^^^
  File "G:\git\electron\src\build\vs_toolchain.py", line 581, in main
    return commands[sys.argv[1]](*sys.argv[2:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\git\electron\src\build\vs_toolchain.py", line 529, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Users\34262\.electron_build_tools\third_party\depot_tools\bootstrap-2@3_11_8_chromium_35_bin\python3\bin\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\34262\\.electron_build_tools\\third_party\\depot_tools\\bootstrap-2@3_11_8_chromium_35_bin\\python3\\bin\\python3.exe', 'G:\\git\\electron\\src\\third_party\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'G:\\git\\electron\\src\\build\\win_toolchain.json', '3a908a0f94', '--force']' returned non-zero exit status 1.
```

### To Reproduce

do as Expected Behavior

### Screenshots

![image](https://github.com/electron/build-tools/assets/17848159/58d9b514-52fb-46fc-8dd9-6d06ceb348df)

### Additional Information

I think this is not relate to https://github.com/electron/build-tools/issues/293, I have check `vs_toolchain.py`, it has apply the py3 compatible patch

should I set `"DEPOT_TOOLS_WIN_TOOLCHAIN": 0"?

**Comment by githoniel** [comment]
I have solved by set `DEPOT_TOOLS_WIN_TOOLCHAIN: 0`, `reclient: 0` and install VS2022 local. After read other issue I found this tool is aim at build last or newer branch of electron
