### ISSUE TITLE
electron build failing 

### ISSUE THREAD

**Issue by muraliran** [electron/build-tools#60]
As indicated in
https://github.com/electron/electron/issues/21835

To me this does not look to be a "build-tools" problem but the source tree is having invalid entries. But my issue was closed and told to file it here.

The command used here was "e init ... --bootstrap testing" resulted in the failure below.

Failure cause is the path to npx.cmd isn't defined. If I override manually at the shell, then it errors out for npx-cli.js misplaced. The errors will compound. The patches or something is screwing up the paths and location where files need to be unzipped at.

Besides this, the build-tools wasn't working initially many times, it just gets stuck after init command displaying contents of .gclient and do nothing for more than 20 minutes. I had multi level folder like "my-electron/master". Switched to single level, set the nodist to v12.8.1 and not sure what else, this morning it started to pull code. But took a lot longer than standard gclient sync. Maybe network was busy during the day.

And there is no option to checkout a branch I created in my local repo of electron (such as " gclient sync -r release/v8.0.0-beta.7 --with_branch_heads --with_tags")

```
Applying: Revert "crypto: add oaepLabel option"
Applying: refactor: TransferrableModule is deprecated, use CompiledWasmModule instead
Applying: enable 31 bit smis on 64bit arch and ptr compression
Applying: fix: remove unused llhttp variables
Applying: fix: include libuv header in node_binding
Applying: remove deprecated task API override removed in latest v8
Hook 'vpython.bat src/electron/script/apply_all_patches.py src/electron/patches/config.json' took 234.87 secs
________ running 'python3 src/electron/script/update-external-binaries.py' in 'C:\Users\muralir-hf\bt-electron'
Downloading https://github.com/electron/electron-frameworks/releases/download/v1.4.1/directxsdk-x64.zip to C:\Users\MURALI~1\AppData\Local\Temp\electron-cb0z92ox\directxsdk-x64.zip
Download directxsdk-x64.zip     1806291  [180629100.0%]
Downloading https://github.com/electron/electron-frameworks/releases/download/v1.4.1/sccache-win32-x64.zip to C:\Users\MURALI~1\AppData\Local\Temp\electron-0u_cwsuz\sccache-win32-x64.zip
Download sccache-win32-x64.zip     4151947  [103798675.0%]
Downloading https://github.com/electron/electron-frameworks/releases/download/v1.4.1/goma-win.zip to C:\Users\MURALI~1\AppData\Local\Temp\electron-ue1bvdc3\goma-win.zip
Download goma-win.zip    52486903  [1049738060.0%]
Hook 'python3 src/electron/script/update-external-binaries.py' took 52.53 secs
________ running 'vpython.bat -c import os, subprocess; os.chdir(os.path.join("src", "electron")); subprocess.check_call(["pyt    npx(*sys.argv[1:])
  File "script/lib/npx.py", line 7, in npx
    subprocess.check_call(call_args)
  File "C:\Users\muralir-hf\sdev\build-tools\src\third_party\depot_tools\bootstrap-3_8_0_chromium_8_bin\python\bin\Lib\subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\muralir-hf\sdev\build-tools\src\third_party\depot_tools\bootstrap-3_8_0_chromium_8_bin\python\bin\Lib\subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Users\muralir-hf\sdev\build-tools\src\third_party\depot_tools\bootstrap-3_8_0_chromium_8_bin\python\bin\Lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Users\muralir-hf\sdev\build-tools\src\third_party\depot_tools\bootstrap-3_8_0_chromium_8_bin\python\bin\Lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\muralir-hf\sdev\build-tools\src\third_party\depot_tools\bootstrap-3_8_0_chromium_8_bin\python\bin\Lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'script/lib/npx.py', 'yarn@1.15.2', 'install', '--frozen-lockfile']' returned non-zero exit status 1
Error: Command 'vpython.bat -c import os, subprocess; os.chdir(os.path.join("src", "electron")); subprocess.check_call(["python", "script/lib/npx.py", "yarn@1.15.2", "install", "--frozen-lockfile"]);' returned non-zero exit status 1 in C:\Users\muralir-hf\bt-electron
ERROR Error: Command failed: python C:\Users\muralir-hf\sdev\build-tools\src\third_party\depot_tools\gclient.py sync --with_branch_heads --with_tags -v
    at checkExecSyncError (child_process.js:621:11)
    at Object.execFileSync (child_process.js:639:15)
    at Object.depotExecFileSync [as execFileSync] (C:\Users\muralir-hf\sdev\build-tools\src\utils\depot-tools.js:80:16)
    at runGClientSync (C:\Users\muralir-hf\sdev\build-tools\src\e-sync.js:35:9)
    at Object.<anonymous> (C:\Users\muralir-hf\sdev\build-tools\src\e-sync.js:48:3)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10)
ERROR Error: Command failed: node C:\Users\muralir-hf\sdev\build-tools\src\e sync -v
    at checkExecSyncError (child_process.js:621:11)
    at Object.execFileSync (child_process.js:639:15)
    at Object.<anonymous> (C:\Users\muralir-hf\sdev\build-tools\src\e-init.js:192:18)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by MarshallOfSound** [comment]
@muraliran Do you have `npx` installed?  If you run `npx --help` do you get anything?

**Comment by muraliran** [comment]
The npx was missing. Thank you. Updated on linux and the gsync worked!

Please update the requirements (for all platforms) in https://www.electronjs.org/docs/development/build-instructions-windows#prerequisites -- it will help folks onboarding on electron.

However on Windows we use nodist due to internal tool chain dependency. I need to see how to get around there because nodist does not install npx as yet.

**Comment by muraliran** [comment]
After installing npx in Windows the gclient sync worked. Closing this. Thank you.
