### ISSUE TITLE
Windows build failure: The filename or extension is too long

### ISSUE THREAD

**Issue by jtbandes** [electron/build-tools#675]
I'm experiencing a build failure on Windows due to long path names. Any advice for fixing or working around this would be appreciated. Thank you! 🙏 

### Operating System
GitHub Actions runner - Microsoft Windows Server 2022 / 10.0.20348
`windows-2022` image https://github.com/actions/runner-images/blob/win22/20241021.1/images/windows/Windows2022-Readme.md

### To Reproduce
- `git config --global core.filemode false`
- `git config --global core.autocrlf false`
- `git config --global branch.autosetuprebase always`
- `git config --global core.longpaths true`
  - This was necessary to make `e init` and `e sync` work
- `npm i -g @electron/build-tools@1.2.0`
- `e init mybuilder --import release --reclient none --target-cpu x64`
- `e sync --revision v33.0.2`
- `e build`

### Expected Behavior
Build passes

### Actual Behavior
Build failure:

```
...snip...

[27751/41383] ACTION //components/flags_ui/resources:build_ts(//build/toolchain/win:win_clang_x64)
[27752/41383] CXX obj/third_party/blink/renderer/modules/webcodecs/webcodecs/video_frame.obj
FAILED: obj/third_party/blink/renderer/modules/webcodecs/webcodecs/video_frame.obj 
..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe /c ../../third_party/blink/renderer/modules/webcodecs/video_frame.cc /Foobj/third_party/blink/renderer/modules/webcodecs/webcodecs/video_frame.obj /nologo /showIncludes:user /winsysroot../../third_party/depot_tools/win_toolchain/vs_files/3ba76c5c20 -DUSE_AURA=1 -DOFFICIAL_BUILD -D_HAS_NODISCARD -D_CRT_NONSTDC_NO_WARNINGS -D_WINSOCK_DEPRECATED_NO_WARNINGS "-DCR_CLANG_REVISION=\"llvmorg-20-init-3847-g69c43468-28\"" -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_EXTENSIVE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -DCR_LIBCXX_REVISION=50ab693ecb611942ce4440d8c9ed707ee65ed5e8 -DTEMP_REBUILD_HACK -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=2 -DWIN32 -D_SECURE_ATL -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=NTDDI_WIN10_NI -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBLINK_MODULES_IMPLEMENTATION=1 -DBLINK_IMPLEMENTATION=1 -DINSIDE_BLINK -DCHROMIUM -DLIBYUV_DISABLE_NEON -DLIBYUV_DISABLE_SVE -DLIBYUV_DISABLE_SME -DLIBYUV_DISABLE_LSX -DLIBYUV_DISABLE_LASX -DSK_ENABLE_SKSL -DSK_UNTIL_CRBUG_1187654_IS_FIXED "-DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\"" -DSK_WIN_FONTMGR_NO_SIMULATIONS -DSK_DISABLE_LEGACY_INIT_DECODERS -DSK_DISABLE_LEGACY_BACKEND_TEXTURE_FUNCS -DSK_DISABLE_LEGACY_TEXTURE_INFO_FUNCS -DSK_DISABLE_LEGACY_BACKEND_SEMAPHORE_FUNCS -DSK_DISABLE_LEGACY_GRAPHITE_IMAGES -DSK_DISABLE_LEGACY_DAWN_TEXTURE_INFO_FUNCS -DSK_DISABLE_LEGACY_DAWN_BACKEND_TEXTURE_FUNCS -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DGR_GL_FUNCTION_TYPE=__stdcall -DSK_GANESH "-DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\"" -DSK_GL -DSK_VULKAN=1 -DSK_GRAPHITE -DSK_DAWN -DVK_USE_PLATFORM_WIN32_KHR -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DGOOGLE_PROTOBUF_INTERNAL_DONATE_STEAL_INLINE=0 "-DCR_CXX_INCLUDE=\"third_party/rust/chromium_crates_io/vendor/cxx-1.0.128/include/cxx.h\"" -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DWEBRTC_ENABLE_AVX2 -DRTC_ENABLE_WIN_WGC -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_WIN -DABSL_ALLOCATOR_NOTHROW=1 -DLOGGING_INSIDE_WEBRTC -DV8_ARRAY_BUFFER_INTERNAL_FIELD_COUNT=0 -DV8_ARRAY_BUFFER_VIEW_INTERNAL_FIELD_COUNT=0 -DV8_PROMISE_INTERNAL_FIELD_COUNT=1 -DV8_COMPRESS_POINTERS -DV8_COMPRESS_POINTERS_IN_SHARED_CAGE -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_ENABLE_SANDBOX -DV8_DEPRECATION_WARNINGS -DV8_USE_PERFETTO -DV8_HAVE_TARGET_OS -DV8_TARGET_OS_WIN -DCPPGC_CAGED_HEAP -DCPPGC_YOUNG_GENERATION -DCPPGC_POINTER_COMPRESSION -DCPPGC_ENABLE_LARGER_CAGE -DCPPGC_SLIM_WRITE_BARRIER -DCRASHPAD_ZLIB_SOURCE_EXTERNAL -DLEVELDB_PLATFORM_CHROMIUM=1 -DWTF_USE_WEBAUDIO_PFFFT=1 -DUSE_LIBJPEG_TURBO=1 -DMANGLE_JPEG_NAMES -DWEBP_EXTERN=extern -DLIBXSLT_STATIC -DLIBGAV1_MAX_BITDEPTH=10 -DLIBGAV1_THREADPOOL_USE_STD_MUTEX -DLIBGAV1_ENABLE_LOGGING=0 -DLIBGAV1_PUBLIC= -I../.. -Igen -I../../buildtools/third_party/libc++ -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../net/third_party/quiche/overrides -I../../net/third_party/quiche/src/quiche/common/platform/default -I../../net/third_party/quiche/src -I../../third_party/libyuv/include -I../../third_party/skia -Igen/third_party/skia -I../../third_party/wuffs/src/release/c -I../../third_party/vulkan/include -I../../third_party/vulkan-headers/src/include -Igen/third_party/dawn/include -I../../third_party/dawn/include -I../../third_party/khronos -I../../gpu -I../../third_party/protobuf/src -Igen/protoc_out -I../../base/allocator/partition_allocator/src -Igen/base/allocator/partition_allocator/src -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/ipcz/include -I../../third_party/ced/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -Igen/net/third_party/quiche/src -I../../third_party/webrtc_overrides -I../../third_party/webrtc -Igen/third_party/webrtc -I../../v8/include -I../../third_party/crashpad/crashpad -I../../third_party/crashpad/crashpad/compat/win -I../../third_party/zlib -I../../third_party/libwebm/source -I../../third_party/angle/include -I../../third_party/mesa_headers -I../../third_party/leveldatabase -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase/src/include -I../../third_party/libaom/source/libaom -I../../third_party/libaom/source/config/win/x64 -I../../third_party/libjpeg_turbo -I../../third_party/libpng -I../../third_party/libwebp/src/src -I../../third_party/ots/src/include -Igen/v8/include -I../../third_party/fp16/src/include -I../../third_party/libxml/src/include -I../../third_party/libxml/win32/include -I../../third_party/libxslt/src -I../../third_party/re2/src -I../../third_party/opus/src/include -I../../third_party/libgav1/src -I../../third_party/libgav1/src/src -I../../third_party/libvpx/source/libvpx -I../../third_party/libvpx/source/config/win/x64 /W4 -Wimplicit-fallthrough -Wextra-semi -Wunreachable-code-aggressive -Wthread-safety -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unneeded-internal-declaration -Wno-nonportable-include-path -Wno-cast-function-type -Wno-vla-extension -Wno-thread-safety-reference-return -Wshadow /WX -fno-delete-null-pointer-checks -fno-ident -fcolor-diagnostics -fmerge-all-constants /Zc:sizedDealloc- -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -mllvm -split-threshold-for-reg-with-hint=0 /clang:-ffp-contract=off -flto=thin -fsplit-lto-unit -mllvm -inlinehint-threshold=360 -fwhole-program-vtables -fcomplete-member-pointers /Gy /FS /bigobj /utf-8 /Zc:twoPhase -ffile-reproducible /Zc:sizedDealloc- /D__WRL_ENABLE_FUNCTION_STATICS__ -fmsc-version=1934 -m64 -msse3 -ffile-compilation-dir=. -no-canonical-prefixes -ftrivial-auto-var-init=pattern /O2 /clang:-O2 /Oy- /Zc:inline /Gw /clang:-fno-math-errno -fprofile-use=../../chrome/build/pgo_profiles/chrome-win64-6723-1728903467-05e59be9539d795e6371504814601424a09f466a-45b0b8ebcc6ea793146b07b91714f7085008c8e5.profdata -Wno-profile-instr-unprofiled -Wno-profile-instr-out-of-date -Wno-backend-plugin /guard:cf /MT -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang span-ctor-from-string-literal -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ref-template-as-trivial-member -Xclang -plugin-arg-find-bad-constructs -Xclang raw-span-template-as-trivial-member -Xclang -plugin-arg-find-bad-constructs -Xclang check-stack-allocated -Xclang -add-plugin -Xclang raw-ptr-plugin -Xclang -plugin-arg-raw-ptr-plugin -Xclang check-raw-ptr-to-stack-allocated -Xclang -plugin-arg-raw-ptr-plugin -Xclang disable-check-raw-ptr-to-stack-allocated-error -Xclang -plugin-arg-raw-ptr-plugin -Xclang raw-ptr-exclude-path=../../third_party/dawn/ /wd4305 /wd4324 /wd4714 /wd4800 -Xclang -plugin-arg-find-bad-constructs -Xclang check-blink-data-member-type -Xclang -add-plugin -Xclang blink-gc-plugin -Wexit-time-destructors -Wglobal-constructors -Wconversion -Wno-float-conversion -Wno-sign-conversion -Wno-implicit-float-conversion -Wno-implicit-int-conversion /Z7 -gno-codeview-command-line -gcodeview-ghash -gomit-unreferenced-methods -Xclang -fuse-ctor-homing -Wno-redundant-parens -Wno-redundant-parens -DPROTOBUF_ALLOW_DEPRECATED=1 /wd4344 -DLIBXML_STATIC= -Wno-invalid-offsetof -Wenum-compare-conditional -Wno-c++11-narrowing-const-reference -Wno-missing-template-arg-list-after-template-kw -Wno-dangling-assignment-gsl /std:c++20 -Wno-trigraphs /TP /GR- -I../../third_party/libc++/src/include /Fd"obj/third_party/blink/renderer/modules/webcodecs/webcodecs_cc.pdb"
Note: including file: ../..\third_party/blink/renderer/modules/webcodecs/video_frame.h
Note: including file:  ../../third_party/libc++/src/include\stdint.h
Note: including file:   ../../third_party/libc++/src/include\__config
...snip...
Note: including file:    ../../third_party/libc++/src/include\__chrono/tzdb.h
Note: including file:    ../../third_party/libc++/src/include\__chrono/tzdb_list.h

GetFullPathNameA(gen/third_party/blink/renderer/bindings/modules/v8/v8_union_cssimagevalue_htmlcanvaselement_htmlimageelement_htmlvideoelement_imagebitmap_offscreencanvas_svgimageelement_videoframe.h): The filename or extension is too long.

[27753/41383] CXX obj/components/safe_browsing/core/common/safe_browsing_prefs/safe_browsing_prefs.obj
[27754/41383] CXX obj/components/security_interstitials/content/proto/ssl_error_assistant.pb.obj
[27755/41383] CXX obj/components/language/core/browser/browser/language_model.obj
[27756/41383] CXX obj/components/safe_browsing/core/browser/db/safebrowsing_proto/safebrowsing.pb.obj
[27757/41383] CXX obj/components/policy/core/common/util/cloud_policy_util.obj
[27758/41383] CXX obj/components/language/core/browser/browser/accept_languages_service.obj
[27759/41383] CXX obj/components/language/core/browser/browser/language_model_manager.obj
[27760/41383] CXX obj/components/language/core/browser/browser/language_usage_metrics.obj
[27761/41383] CXX obj/components/language/core/browser/browser/language_prefs.obj
ninja: build stopped: subcommand failed.
ERROR Error: Command failed: ninja.bat electron
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at Object.execFileSync (node:child_process:927:15)
    at Object.depotExecFileSync [as execFileSync] (C:\Users\runneradmin\.electron_build_tools\src\utils\depot-tools.js:147:23)
    at runNinja (C:\Users\runneradmin\.electron_build_tools\src\e-build.js:87:9)
    at Command.<anonymous> (C:\Users\runneradmin\.electron_build_tools\src\e-build.js:115:7)
    at Command.listener [as _actionHandler] (C:\Users\runneradmin\.electron_build_tools\node_modules\commander\lib\command.js:480:17)
    at C:\Users\runneradmin\.electron_build_tools\node_modules\commander\lib\command.js:1234:65
    at Command._chainOrCall (C:\Users\runneradmin\.electron_build_tools\node_modules\commander\lib\command.js:1151:12)
```

**Comment by jtbandes** [comment]
May be related to https://github.com/ninja-build/ninja/issues/2359 / https://github.com/ninja-build/ninja/issues/1900 ?

**Comment by jtbandes** [comment]
I've tried a couple things to work around this:

- Use `cmd.exe` (found this suggestion somewhere although I forgot where)
- Run `New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force` before the build (sounds like it helped in https://github.com/ninja-build/ninja/issues/1900)

However things are still not working. I wonder if the version of ninja being used is not the one I thought I found in DEPS?

**Comment by dbger** [comment]
> May be related to [ninja-build/ninja#2359](https://github.com/ninja-build/ninja/issues/2359) / [ninja-build/ninja#1900](https://github.com/ninja-build/ninja/issues/1900) ?
> 
> However, it appears that DEPS already specifies ninja 1.12.1.

You can try the old version 1.8.2.

**Comment by jtbandes** [comment]
How would I do that? Modify DEPS?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by jtbandes** [comment]
@codebytere I've just tried removing `--reclient none` and got the same build error (now using latest versions of electron 37.2.0 and build-tools 2.1.1).

In this case I was using a Windows 2022 github x64 actions runner.

Output from `e init mybuilder --import release --target-cpu x64`:
```
...
Running "C:\Users\runneradmin\.electron_build_tools\third_party\reclient\electron-rbe-credential-helper.exe login"
Authentication Status: Authenticated
Since:     2025-07-04 22:22:25 +0000 UTC
Expires:   2025-07-05 10:22:25 +0000 UTC
Cluster:   cas.notgoma.com
Principal: anon/ci/gha/1/merge
Access:    Cache Only
```

Output from `e build`:
```
...
FAILED: obj/third_party/blink/renderer/modules/webcodecs/webcodecs/video_frame.obj 
...
GetFullPathNameA(gen/third_party/blink/renderer/bindings/modules/v8/v8_union_cssimagevalue_htmlcanvaselement_htmlimageelement_htmlvideoelement_imagebitmap_offscreencanvas_svgimageelement_videoframe.h): The filename or extension is too long.
...
ninja: build stopped: subcommand failed.
RBE Stats: down 4.59 GB, up 0 B, 9406 cache hits, 15032 local fallbacks
ERROR Error: Command failed: autoninja.bat -j 200 electron
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:883:11)
    at Object.execFileSync (node:child_process:919:15)
    at Object.depotExecFileSync [as execFileSync] (C:\Users\runneradmin\.electron_build_tools\src\utils\depot-tools.js:146:23)
    at runNinja (C:\Users\runneradmin\.electron_build_tools\src\e-build.js:96:9)
    at Command.<anonymous> (C:\Users\runneradmin\.electron_build_tools\src\e-build.js:134:7)
```

Any further ideas?

**Comment by codebytere** [comment]
@jtbandes it actually looks like ninja is going to address this - https://github.com/ninja-build/ninja/pull/2552
