### ISSUE TITLE
MacOS 10.15.3, xcode 11.3 fails for build-tools, electron builds etc

### ISSUE THREAD

**Issue by muraliran** [electron/build-tools#79]
If I could get the requirements for getting electron build on latest macos & xcode, it will be really helpful.

**Using build-tools, in pre-requisites, fails here:**
build-tools murali-hf$ e load-xcode
Creating /Users/murali-hf/sdev/ftl-electron/build-tools/third_party/Xcode
Downloading "https://electron-build-tools.s3-us-west-2.amazonaws.com/macos/Xcode-10.3.zip" into /Users/murali-hf/sdev/ftl-electron/build-tools/third_party/Xcode/Xcode.zip
[=========================================================================================================] 29257222/bps 100% 0.0s
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, rename '/Users/murali-hf/sdev/ftl-electron/build-tools/third_party/Xcode/tmp_unzip/Xcode.app' -> '/Users/murali-hf/sdev/ftl-electron/build-tools/third_party/Xcode/Xcode.app'
    at Object.renameSync (fs.js:643:3)
    at Object.ensureXcode (/Users/murali-hf/sdev/ftl-electron/build-tools/src/utils/xcode.js:48:8)
    at Object.<anonymous> (/Users/murali-hf/sdev/ftl-electron/build-tools/src/e-load-xcode.js:16:7)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -2,
  syscall: 'rename',
  code: 'ENOENT',
  path: '/Users/murali-hf/sdev/ftl-electron/build-tools/third_party/Xcode/tmp_unzip/Xcode.app',
  dest: '/Users/murali-hf/sdev/ftl-electron/build-tools/third_party/Xcode/Xcode.app'
}_

**If I ignore & continue further, e build fails:**
MR-MBP:build-tools murali-hf$ e build electron
Running "goma_ctl.py ensure_start" in /Users/murali-hf/sdev/ftl-electron/build-tools/third_party/goma
ERROR Error: spawnSync python ENOENT
    at Object.spawnSync (internal/child_process.js:1041:20)
    at spawnSync (child_process.js:607:24)
    at Object.execFileSync (child_process.js:634:15)
    at Object.ensureGomaStart [as ensure] (/Users/murali-hf/sdev/ftl-electron/build-tools/src/utils/goma.js:113:16)
    at runNinja (/Users/murali-hf/sdev/ftl-electron/build-tools/src/e-build.js:46:10)
    at Object.<anonymous> (/Users/murali-hf/sdev/ftl-electron/build-tools/src/e-build.js:102:3)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)

**And using electron-gn builds, it fails at** 
.... 
../../electron/external_binaries -fobjc-weak -std=c++14 -stdlib=libc++ -fobjc-call-cxx-cdtors -Wobjc-missing-property-synthesis -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../electron/shell/browser/mac/atom_application_delegate.mm -o obj/electron/electron_lib/atom_application_delegate.o
../../electron/shell/browser/mac/atom_application_delegate.mm:36:60: error: too many arguments to function call, expected 0, have 5
  g_swizzle_imk_input_session->GetOriginalImplementation()(self, _cmd, range,
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~
1 error generated.
[58/883] CXX obj/electron/electron_lib/network_hints_handler_impl.o

**Comment by muraliran** [comment]
An Update. I was able to build if I xcode-select the Developer in Xcode v 10.3. But fails with 11.3.

**Comment by MarshallOfSound** [comment]
@muraliran Please use `e load-xcode` to get the correct version of Xcode, Electron builds require very specific dependency versions
