### ISSUE TITLE
Initializing in root directory fails to create .gclient config

### ISSUE THREAD

**Issue by samuelmaddock** [electron/build-tools#87]
When initializing the code on Windows, the process fails due to `.gclient` file not existing. I'm going to keep this issue open while I work through fixing it.

```
Sam@blackmesa MINGW64 /d/work/electron/master
$ e init --root=./ --bootstrap testing
New build config testing created in D:\work\build-tools\configs\evm.testing.json
Now using config testing
Creating D:\work\electron\master\src
Running "python D:\work\build-tools\third_party\depot_tools\gclient.py sync --with_branch_heads --with_tags -v --ignore_locks" in D:\work\electron\master\src
Looking for .gclient starting from D:\work\electron\master\src

Couldn't find configuration file.
Error: client not configured; see 'gclient config'
ERROR Error: Command failed: python D:\work\build-tools\third_party\depot_tools\gclient.py sync --with_branch_heads --with_tags -v --ignore_locks
    at checkExecSyncError (child_process.js:630:11)
    at Object.execFileSync (child_process.js:648:15)
    at Object.depotExecFileSync [as execFileSync] (D:\work\build-tools\src\utils\depot-tools.js:86:16)
    at runGClientSync (D:\work\build-tools\src\e-sync.js:35:9)
    at Object.<anonymous> (D:\work\build-tools\src\e-sync.js:48:3)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) 
ERROR Error: Command failed: node D:\work\build-tools\src\e sync -v --ignore_locks      
    at checkExecSyncError (child_process.js:630:11)
    at Object.execFileSync (child_process.js:648:15)
    at Object.<anonymous> (D:\work\build-tools\src\e-init.js:183:18)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) 
    at internal/main/run_main_module.js:18:47
```

---

One pain point I came across is that when the command fails, the user needs to know to delete `build-tools/configs/evm.testing.json` or else it can't be re-run.

**Comment by samuelmaddock** [comment]
Figured out the issue, I was setting the root to the current directory (`--root=./`). This will cause the init script to skip creating the `.gclient` config.
https://github.com/electron/build-tools/blob/master/src/e-init.js#L89-L94

**Comment by xland** [comment]
How about this issue's progress?


what happened now:
```
D:\project\electronBuild>e init --root=./ --bootstrap testing
New build config testing created in C:\Users\Administrator\.electron_build_tools\configs\evm.testing.json
Now using config testing
Creating D:\project\electronBuild\src
Running "python C:\Users\Administrator\.electron_build_tools\third_party\depot_tools\gclient.py sync --with_branch_heads --with_tags -vv -v" in D:\project\electronBuild\src
Looking for .gclient starting from D:\project\electronBuild\src

Couldn't find configuration file.
Error: client not configured; see 'gclient config'
ERROR Error: Command failed: python C:\Users\Administrator\.electron_build_tools\third_party\depot_tools\gclient.py sync --with_branch_heads --with_tags -vv -v
    at checkExecSyncError (child_process.js:621:11)
    at Object.execFileSync (child_process.js:639:15)
    at Object.depotExecFileSync [as execFileSync] (C:\Users\Administrator\.electron_build_tools\src\utils\depot-tools.js:117:16)
    at runGClientSync (C:\Users\Administrator\.electron_build_tools\src\e-sync.js:54:9)
    at Object.<anonymous> (C:\Users\Administrator\.electron_build_tools\src\e-sync.js:76:3)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
ERROR Error: Command failed: C:\Program Files\nodejs\node.exe C:\Users\Administrator\.electron_build_tools\src\e sync -v
    at checkExecSyncError (child_process.js:621:11)
    at Object.execFileSync (child_process.js:639:15)
    at Object.<anonymous> (C:\Users\Administrator\.electron_build_tools\src\e-init.js:201:18)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by litterye** [comment]
How about this issue's progress?

**Comment by llbo** [comment]
Is there anyone working on this issue
