### ISSUE TITLE
Goma build dependency fails to install

### ISSUE THREAD

**Issue by samuelmaddock** [electron/build-tools#89]
OS: Windows 10 Pro 64-bit (Build 18362)
Node: v12.16.0
NPM: 6.2.0
Yarn: 1.19.1

After running `e init --root=~/electron --bootstrap testing`, I eventually receive a failure with the following error log:
```
Downloading https://electron-build-tools.s3-us-west-2.amazonaws.com/build-dependencies/f97c88aa5d49395ae20387b6329ad406fd019f5fb4aac4ba639ca928b7151f6b/goma-win.zip to C:\Users\Sam\AppData\Local\Temp\electron-s3t4p345\goma-win.zip
Download goma-win.zip    52486903  [1049738060.0%] 

...

________ running 'vpython.bat -vpython-spec src/.vpython -vpython-tool install' in 'D:\work\electron\master'
Writing new goma.gn file D:\work\build-tools\third_party\goma.gn
Downloading "https://electron-build-tools.s3-us-west-2.amazonaws.com/build-dependencies/d13f5e07c3306fa0367a662feea6133870e30a03767c23123da72a4e3a385d2e/goma-win.zip" into D:\work\build-tools\third_party\goma-win.zip
[====================================================================================================================================================] 17581491/bps 100% 0.0s 
Running "goma_ctl.py ensure_start" in D:\work\build-tools\third_party\goma
Traceback (most recent call last):
  File "goma_ctl.py", line 3164, in <module>
    sys.exit(main())
  File "goma_ctl.py", line 3158, in main
    goma = GetGomaDriver()
  File "goma_ctl.py", line 3152, in GetGomaDriver
    env = _GOMA_ENVS[os.name]()
  File "goma_ctl.py", line 2485, in __init__
    raise e
ImportError: No module named win32process
Exception AttributeError: "'GomaEnvWin' object has no attribute '_delete_tmp_dir'" in <bound method GomaEnvWin.__del__ of <__main__.GomaEnvWin object at 0x0351FB90>> ignored 
ERROR Error: Command failed: python goma_ctl.py ensure_start
Traceback (most recent call last):
  File "goma_ctl.py", line 3164, in <module>
    sys.exit(main())
  File "goma_ctl.py", line 3158, in main
    goma = GetGomaDriver()
  File "goma_ctl.py", line 3152, in GetGomaDriver
    env = _GOMA_ENVS[os.name]()
  File "goma_ctl.py", line 2485, in __init__
    raise e
ImportError: No module named win32process
Exception AttributeError: "'GomaEnvWin' object has no attribute '_delete_tmp_dir'" in <bound method GomaEnvWin.__del__ of <__main__.GomaEnvWin object at 0x0351FB90>> ignored 

    at checkExecSyncError (child_process.js:630:11)
    at Object.execFileSync (child_process.js:648:15)
    at Object.ensureGomaStart [as ensure] (D:\work\build-tools\src\utils\goma.js:111:16)
    at runNinja (D:\work\build-tools\src\e-build.js:49:10)
    at Object.<anonymous> (D:\work\build-tools\src\e-build.js:105:3)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
ERROR Error: Command failed: node D:\work\build-tools\src\e build
    at checkExecSyncError (child_process.js:630:11)
    at Object.execFileSync (child_process.js:648:15)
    at Object.<anonymous> (D:\work\build-tools\src\e-init.js:202:18)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

Running `e sync` then `e build` after receiving this error results in the same exception.
```
$ e build
Running "goma_ctl.py ensure_start" in D:\work\build-tools\third_party\goma
Traceback (most recent call last):
  File "goma_ctl.py", line 3164, in <module>
    sys.exit(main())
  File "goma_ctl.py", line 3158, in main
    goma = GetGomaDriver()
  File "goma_ctl.py", line 3152, in GetGomaDriver
    env = _GOMA_ENVS[os.name]()
  File "goma_ctl.py", line 2485, in __init__
    raise e
ImportError: No module named win32process
Exception AttributeError: "'GomaEnvWin' object has no attribute '_delete_tmp_dir'" in <bound method GomaEnvWin.__del__ of <__main__.GomaEnvWin object at 0x03824B90>> ignored 
ERROR Error: Command failed: python goma_ctl.py ensure_start
Traceback (most recent call last):
  File "goma_ctl.py", line 3164, in <module>
    sys.exit(main())
  File "goma_ctl.py", line 3158, in main
    goma = GetGomaDriver()
  File "goma_ctl.py", line 3152, in GetGomaDriver
    env = _GOMA_ENVS[os.name]()
  File "goma_ctl.py", line 2485, in __init__
    raise e
ImportError: No module named win32process
Exception AttributeError: "'GomaEnvWin' object has no attribute '_delete_tmp_dir'" in <bound method GomaEnvWin.__del__ of <__main__.GomaEnvWin object at 0x03824B90>> ignored 

    at checkExecSyncError (child_process.js:630:11)
    at Object.execFileSync (child_process.js:648:15)
    at Object.ensureGomaStart [as ensure] (D:\work\build-tools\src\utils\goma.js:111:16)
    at runNinja (D:\work\build-tools\src\e-build.js:49:10)
    at Object.<anonymous> (D:\work\build-tools\src\e-build.js:105:3)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
```

**Comment by MarshallOfSound** [comment]
Have you installed pywin32?

**Comment by samuelmaddock** [comment]
> 
> 
> Have you installed pywin32?

Ah, it doesn't appear that I do. I think the command may be using my local installed copy of Python 2.7 instead of what's distributed with depot_tools.

The lack of `pywin32` is made clear when running `goma_ctl.py` directly.
```
$ ./third_party/goma/goma_ctl.py --version ensure_start
You don't seem to have installed pywin32 module, `pip install pywin32` or `python -m pip install pywin32` may fix.
Traceback (most recent call last):
  File "./third_party/goma/goma_ctl.py", line 3164, in <module>
    sys.exit(main())
  File "./third_party/goma/goma_ctl.py", line 3158, in main
    goma = GetGomaDriver()
  File "./third_party/goma/goma_ctl.py", line 3152, in GetGomaDriver
    env = _GOMA_ENVS[os.name]()
  File "./third_party/goma/goma_ctl.py", line 2485, in __init__
    raise e
ImportError: No module named win32process
Exception AttributeError: "'GomaEnvWin' object has no attribute '_delete_tmp_dir'" in <bound method GomaEnvWin.__del__ of <__main__.GomaEnvWin object at 0x035EE110>> ignored
```

**Comment by samuelmaddock** [comment]
Fixed by installing Python prerequisites as defined in the [Electron build instructions for Windows](https://www.electronjs.org/docs/development/build-instructions-windows#prerequisites).
