### ISSUE TITLE
build electron on MacOS, getting the code steps, "gclient sync" command fail

### ISSUE THREAD

**Issue by evgen-ai** [electron/build-tools#94]
I am build electron on MacOS.
While getting the code steps,
I found a problem using the command "gclient sync --with_branch_heads --with_tags",
Please help me out.
Issue is reproduced on 3 different macbooks.

System: MacOS 10.14.6

```
________ running 'vpython src/electron/script/apply_all_patches.py src/electron/patches/config.json' in '/Users/user/Documents/webrtc/electron_gn'
...
Applying: feat: enable passing cli flags
Hook 'vpython src/electron/script/apply_all_patches.py src/electron/patches/config.json' took 371.61 secs
Traceback (most recent call last):on_external_binaries
  File "/Users/user/Documents/webrtc/depot_tools/metrics.py", line 267, in print_notice_and_exit
    yield
  File "/Users/user/Documents/webrtc/depot_tools/gclient.py", line 3182, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/user/Documents/webrtc/depot_tools/gclient.py", line 3168, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/Users/user/Documents/webrtc/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/Users/user/Documents/webrtc/depot_tools/gclient.py", line 2725, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/Users/user/Documents/webrtc/depot_tools/gclient.py", line 1797, in RunOnDeps
    self.RunHooksRecursively(self._options, pm)
  File "/Users/user/Documents/webrtc/depot_tools/gclient.py", line 1083, in RunHooksRecursively
    hook.run()
  File "/Users/user/Documents/webrtc/depot_tools/gclient.py", line 259, in run
    always_show_header=self._verbose)
  File "/Users/user/Documents/webrtc/depot_tools/gclient_utils.py", line 549, in CheckCallAndFilter
    **kwargs)
  File "/Users/user/Documents/webrtc/depot_tools/subprocess2.py", line 170, in __init__
    % (str(e), kwargs.get('cwd'), args[0]))
OSError: Execution failed with error: [Errno 2] No such file or directory.
Check that /Users/user/Documents/webrtc/electron_gn or python3 exist and have execution permission.
```

**Comment by MarshallOfSound** [comment]
`brew install python3`

**Comment by pergy** [comment]
So, is python 3 is required for electron build? I don't see that mentioned anywhere.
